#include <string>
namespace slg { namespace ocl {
std::string KernelSource_biaspathocl_kernels_mega = 
"#line 2 \"biaspatchocl_kernels_mega.cl\"\n"
"\n"
"/***************************************************************************\n"
" * Copyright 1998-2013 by authors (see AUTHORS.txt)                        *\n"
" *                                                                         *\n"
" *   This file is part of LuxRender.                                       *\n"
" *                                                                         *\n"
" * Licensed under the Apache License, Version 2.0 (the \"License\");         *\n"
" * you may not use this file except in compliance with the License.        *\n"
" * You may obtain a copy of the License at                                 *\n"
" *                                                                         *\n"
" *     http://www.apache.org/licenses/LICENSE-2.0                          *\n"
" *                                                                         *\n"
" * Unless required by applicable law or agreed to in writing, software     *\n"
" * distributed under the License is distributed on an \"AS IS\" BASIS,       *\n"
" * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.*\n"
" * See the License for the specific language governing permissions and     *\n"
" * limitations under the License.                                          *\n"
" ***************************************************************************/\n"
"\n"
"// List of symbols defined at compile time:\n"
"//  PARAM_TASK_COUNT\n"
"//  PARAM_TILE_SIZE\n"
"//  PARAM_FIRST_VERTEX_DL_COUNT\n"
"//  PARAM_RADIANCE_CLAMP_MAXVALUE\n"
"//  PARAM_PDF_CLAMP_VALUE\n"
"//  PARAM_AA_SAMPLES\n"
"//  PARAM_DIRECT_LIGHT_SAMPLES\n"
"//  PARAM_DIFFUSE_SAMPLES\n"
"//  PARAM_GLOSSY_SAMPLES\n"
"//  PARAM_SPECULAR_SAMPLES\n"
"//  PARAM_DEPTH_MAX\n"
"//  PARAM_DEPTH_DIFFUSE_MAX\n"
"//  PARAM_DEPTH_GLOSSY_MAX\n"
"//  PARAM_DEPTH_SPECULAR_MAX\n"
"//  PARAM_IMAGE_FILTER_WIDTH\n"
"//  PARAM_LOW_LIGHT_THREASHOLD\n"
"//  PARAM_NEAR_START_LIGHT\n"
"\n"
"//------------------------------------------------------------------------------\n"
"// RenderSample (Mega-Kernel)\n"
"//------------------------------------------------------------------------------\n"
"\n"
"__kernel __attribute__((work_group_size_hint(64, 1, 1))) void RenderSample(\n"
"		KERNEL_ARGS\n"
"		) {\n"
"	const size_t gid = get_global_id(0);\n"
"\n"
"	const uint sampleIndex = gid % (PARAM_AA_SAMPLES * PARAM_AA_SAMPLES);\n"
"	const uint samplePixelIndex = gid / (PARAM_AA_SAMPLES * PARAM_AA_SAMPLES);\n"
"	const uint samplePixelX = samplePixelIndex % PARAM_TILE_SIZE;\n"
"	const uint samplePixelY = samplePixelIndex / PARAM_TILE_SIZE;\n"
"\n"
"	if ((gid >= PARAM_TILE_SIZE * PARAM_TILE_SIZE * PARAM_AA_SAMPLES * PARAM_AA_SAMPLES) ||\n"
"			(tileStartX + samplePixelX >= engineFilmWidth) ||\n"
"			(tileStartY + samplePixelY >= engineFilmHeight))\n"
"		return;\n"
"\n"
"	__global GPUTask *task = &tasks[gid];\n"
"	__global GPUTaskDirectLight *taskDirectLight = &tasksDirectLight[gid];\n"
"	__global GPUTaskPathVertexN *taskPathVertexN = &tasksPathVertexN[gid];\n"
"	__global GPUTaskStats *taskStat = &taskStats[gid];\n"
"\n"
"	//--------------------------------------------------------------------------\n"
"	// Initialize image maps page pointer table\n"
"	//--------------------------------------------------------------------------\n"
"\n"
"	INIT_IMAGEMAPS_PAGES\n"
"\n"
"	//--------------------------------------------------------------------------\n"
"	// Initialize the eye ray\n"
"	//--------------------------------------------------------------------------\n"
"\n"
"	// Read the seed\n"
"	Seed seed;\n"
"	seed.s1 = task->seed.s1;\n"
"	seed.s2 = task->seed.s2;\n"
"	seed.s3 = task->seed.s3;\n"
"\n"
"#if defined(PARAM_HAS_VOLUMES)\n"
"	// Initialize the volume information\n"
"	PathVolumeInfo_Init(&task->volInfoPathVertex1);\n"
"#endif\n"
"\n"
"	uint tracedRaysCount = taskStat->raysCount;\n"
"	float3 throughputPathVertex1 = WHITE;\n"
"	\n"
"	__global SampleResult *sampleResult = &taskResults[gid];\n"
"	SampleResult_Init(sampleResult);\n"
"#if defined(PARAM_FILM_CHANNELS_HAS_DIRECT_SHADOW_MASK)\n"
"	sampleResult->directShadowMask = 1.f;\n"
"#endif\n"
"#if defined(PARAM_FILM_CHANNELS_HAS_INDIRECT_SHADOW_MASK)\n"
"	sampleResult->indirectShadowMask = 1.f;\n"
"#endif\n"
"\n"
"	Ray ray;\n"
"	RayHit rayHit;\n"
"	GenerateCameraRay(&seed, task, sampleResult,\n"
"			camera, pixelFilterDistribution,\n"
"			samplePixelX, samplePixelY, sampleIndex,\n"
"			tileStartX, tileStartY,\n"
"			engineFilmWidth, engineFilmHeight, &ray);\n"
"	const float time = ray.time;\n"
"\n"
"	//--------------------------------------------------------------------------\n"
"	// Trace the eye ray\n"
"	//--------------------------------------------------------------------------\n"
"\n"
"	tracedRaysCount += BIASPATHOCL_Scene_Intersect(\n"
"#if defined(PARAM_HAS_VOLUMES)\n"
"		&task->volInfoPathVertex1,\n"
"		&task->tmpHitPoint,\n"
"#endif\n"
"#if defined(PARAM_HAS_PASSTHROUGH)\n"
"		Rnd_FloatValue(&seed),\n"
"#endif\n"
"		&ray, &rayHit,\n"
"		&task->bsdfPathVertex1,\n"
"		&throughputPathVertex1,\n"
"		sampleResult,\n"
"		// BSDF_Init parameters\n"
"		meshDescs,\n"
"		meshMats,\n"
"#if (PARAM_TRIANGLE_LIGHT_COUNT > 0)\n"
"		meshTriLightDefsOffset,\n"
"#endif\n"
"		vertices,\n"
"#if defined(PARAM_HAS_NORMALS_BUFFER)\n"
"		vertNormals,\n"
"#endif\n"
"#if defined(PARAM_HAS_UVS_BUFFER)\n"
"		vertUVs,\n"
"#endif\n"
"#if defined(PARAM_HAS_COLS_BUFFER)\n"
"		vertCols,\n"
"#endif\n"
"#if defined(PARAM_HAS_ALPHAS_BUFFER)\n"
"		vertAlphas,\n"
"#endif\n"
"		triangles\n"
"		MATERIALS_PARAM\n"
"		// Accelerator_Intersect parameters\n"
"		ACCELERATOR_INTERSECT_PARAM);\n"
"\n"
"	//--------------------------------------------------------------------------\n"
"	// Render the eye ray hit point\n"
"	//--------------------------------------------------------------------------\n"
"\n"
"	if (rayHit.meshIndex != NULL_INDEX) {\n"
"		//----------------------------------------------------------------------\n"
"		// Something was hit\n"
"		//----------------------------------------------------------------------\n"
"\n"
"		// Save the path first vertex information\n"
"#if defined(PARAM_FILM_CHANNELS_HAS_ALPHA)\n"
"		sampleResult->alpha = 1.f;\n"
"#endif\n"
"#if defined(PARAM_FILM_CHANNELS_HAS_DEPTH)\n"
"		sampleResult->depth = rayHit.t;\n"
"#endif\n"
"#if defined(PARAM_FILM_CHANNELS_HAS_POSITION)\n"
"		sampleResult->position = task->bsdfPathVertex1.hitPoint.p;\n"
"#endif\n"
"#if defined(PARAM_FILM_CHANNELS_HAS_GEOMETRY_NORMAL)\n"
"		sampleResult->geometryNormal = task->bsdfPathVertex1.hitPoint.geometryN;\n"
"#endif\n"
"#if defined(PARAM_FILM_CHANNELS_HAS_SHADING_NORMAL)\n"
"		sampleResult->shadingNormal = task->bsdfPathVertex1.hitPoint.shadeN;\n"
"#endif\n"
"#if defined(PARAM_FILM_CHANNELS_HAS_MATERIAL_ID)\n"
"		sampleResult->materialID = BSDF_GetMaterialID(&task->bsdfPathVertex1\n"
"			MATERIALS_PARAM);\n"
"#endif\n"
"#if defined(PARAM_FILM_CHANNELS_HAS_UV)\n"
"		sampleResult->uv = task->bsdfPathVertex1.hitPoint.uv;\n"
"#endif\n"
"\n"
"#if (PARAM_TRIANGLE_LIGHT_COUNT > 0)\n"
"		// Check if it is a light source (note: I can hit only triangle area light sources)\n"
"		if (BSDF_IsLightSource(&task->bsdfPathVertex1) && (rayHit.t > PARAM_NEAR_START_LIGHT)) {\n"
"			// SPECULAR is required to avoid MIS\n"
"			DirectHitFiniteLight(SPECULAR,\n"
"					throughputPathVertex1,\n"
"					rayHit.t, &task->bsdfPathVertex1, 1.f,\n"
"					sampleResult\n"
"					LIGHTS_PARAM);\n"
"		}\n"
"#endif\n"
"\n"
"		//----------------------------------------------------------------------\n"
"		// First path vertex direct light sampling\n"
"		//----------------------------------------------------------------------\n"
"\n"
"		const BSDFEvent materialEventTypes = BSDF_GetEventTypes(&task->bsdfPathVertex1\n"
"			MATERIALS_PARAM);\n"
"		sampleResult->lastPathVertex = \n"
"				(PARAM_DEPTH_MAX <= 1) ||\n"
"				(!((PARAM_DEPTH_DIFFUSE_MAX > 0) && (materialEventTypes & DIFFUSE)) &&\n"
"				!((PARAM_DEPTH_GLOSSY_MAX > 0) && (materialEventTypes & GLOSSY)) &&\n"
"				!((PARAM_DEPTH_SPECULAR_MAX > 0) && (materialEventTypes & SPECULAR)));\n"
"\n"
"		// Only if it is not a SPECULAR BSDF\n"
"		if (!BSDF_IsDelta(&task->bsdfPathVertex1\n"
"				MATERIALS_PARAM)) {\n"
"#if defined(PARAM_HAS_VOLUMES)\n"
"			// I need to work on a copy of volume information of the first path vertex\n"
"			taskDirectLight->directLightVolInfo = task->volInfoPathVertex1;\n"
"#endif\n"
"\n"
"			tracedRaysCount +=\n"
"				DirectLightSampling_ALL(\n"
"				&seed,\n"
"#if defined(PARAM_HAS_VOLUMES)\n"
"				&taskDirectLight->directLightVolInfo,\n"
"#endif\n"
"#if (PARAM_TRIANGLE_LIGHT_COUNT > 0) || defined(PARAM_HAS_VOLUMES)\n"
"				&task->tmpHitPoint,\n"
"#endif\n"
"#if defined(PARAM_HAS_INFINITELIGHTS)\n"
"				worldCenterX, worldCenterY, worldCenterZ, worldRadius,\n"
"#endif\n"
"				time,\n"
"				throughputPathVertex1,\n"
"				&task->bsdfPathVertex1, &taskDirectLight->directLightBSDF,\n"
"				sampleResult,\n"
"				// BSDF_Init parameters\n"
"				meshDescs,\n"
"				meshMats,\n"
"				vertices,\n"
"#if defined(PARAM_HAS_NORMALS_BUFFER)\n"
"				vertNormals,\n"
"#endif\n"
"#if defined(PARAM_HAS_UVS_BUFFER)\n"
"				vertUVs,\n"
"#endif\n"
"#if defined(PARAM_HAS_COLS_BUFFER)\n"
"				vertCols,\n"
"#endif\n"
"#if defined(PARAM_HAS_ALPHAS_BUFFER)\n"
"				vertAlphas,\n"
"#endif\n"
"				triangles\n"
"				// Accelerator_Intersect parameters\n"
"				ACCELERATOR_INTERSECT_PARAM\n"
"				// Light related parameters\n"
"				LIGHTS_PARAM);\n"
"		}\n"
"		\n"
"		//----------------------------------------------------------------------\n"
"		// Sample the components of the BSDF of the first path vertex\n"
"		//----------------------------------------------------------------------\n"
"\n"
"#if defined(PARAM_FILM_CHANNELS_HAS_INDIRECT_SHADOW_MASK)\n"
"		sampleResult->indirectShadowMask = 0.f;\n"
"#endif\n"
"\n"
"		if (!sampleResult->lastPathVertex) {\n"
"			sampleResult->firstPathVertex = false;\n"
"\n"
"			BSDFEvent vertex1SampleComponent = DIFFUSE;\n"
"			do {\n"
"				if (PathDepthInfo_CheckComponentDepths(vertex1SampleComponent) && (materialEventTypes & vertex1SampleComponent)) {\n"
"					const int matSamplesCount = mats[task->bsdfPathVertex1.materialIndex].samples;\n"
"					const uint globalMatSamplesCount = ((vertex1SampleComponent == DIFFUSE) ? PARAM_DIFFUSE_SAMPLES :\n"
"						((vertex1SampleComponent == GLOSSY) ? PARAM_GLOSSY_SAMPLES :\n"
"							PARAM_SPECULAR_SAMPLES));\n"
"					const uint sampleCount = (matSamplesCount < 0) ? globalMatSamplesCount : (uint)matSamplesCount;\n"
"\n"
"					tracedRaysCount += SampleComponent(\n"
"							&seed,\n"
"#if defined(PARAM_HAS_VOLUMES)\n"
"							&task->volInfoPathVertex1,\n"
"							&taskPathVertexN->volInfoPathVertexN,\n"
"							&taskDirectLight->directLightVolInfo,\n"
"#endif\n"
"#if (PARAM_TRIANGLE_LIGHT_COUNT > 0) || defined(PARAM_HAS_VOLUMES)\n"
"							&task->tmpHitPoint,\n"
"#endif\n"
"#if defined(PARAM_HAS_INFINITELIGHTS)\n"
"							worldCenterX, worldCenterY, worldCenterZ, worldRadius,\n"
"#endif\n"
"							time,\n"
"							vertex1SampleComponent,\n"
"							sampleCount, throughputPathVertex1,\n"
"							&task->bsdfPathVertex1, &taskPathVertexN->bsdfPathVertexN,\n"
"							&taskDirectLight->directLightBSDF,\n"
"							sampleResult,\n"
"							// BSDF_Init parameters\n"
"							meshDescs,\n"
"							meshMats,\n"
"							vertices,\n"
"#if defined(PARAM_HAS_NORMALS_BUFFER)\n"
"							vertNormals,\n"
"#endif\n"
"#if defined(PARAM_HAS_UVS_BUFFER)\n"
"							vertUVs,\n"
"#endif\n"
"#if defined(PARAM_HAS_COLS_BUFFER)\n"
"							vertCols,\n"
"#endif\n"
"#if defined(PARAM_HAS_ALPHAS_BUFFER)\n"
"							vertAlphas,\n"
"#endif\n"
"							triangles\n"
"							// Accelerator_Intersect parameters\n"
"							ACCELERATOR_INTERSECT_PARAM\n"
"							// Light related parameters\n"
"							LIGHTS_PARAM);\n"
"				}\n"
"\n"
"				// Move to the next BSDF component\n"
"				vertex1SampleComponent = (vertex1SampleComponent == DIFFUSE) ? GLOSSY :\n"
"					((vertex1SampleComponent == GLOSSY) ? SPECULAR : NONE);\n"
"			} while (vertex1SampleComponent != NONE);\n"
"		}\n"
"	} else {\n"
"		//----------------------------------------------------------------------\n"
"		// Nothing was hit\n"
"		//----------------------------------------------------------------------\n"
"\n"
"#if defined(PARAM_HAS_ENVLIGHTS)\n"
"		// Add environmental lights radiance\n"
"		const float3 rayDir = (float3)(ray.d.x, ray.d.y, ray.d.z);\n"
"		// SPECULAR is required to avoid MIS\n"
"		DirectHitInfiniteLight(\n"
"				SPECULAR,\n"
"				throughputPathVertex1,\n"
"				-rayDir, 1.f,\n"
"				sampleResult\n"
"				LIGHTS_PARAM);\n"
"#endif\n"
"\n"
"#if defined(PARAM_FILM_CHANNELS_HAS_ALPHA)\n"
"		sampleResult->alpha = 0.f;\n"
"#endif\n"
"#if defined(PARAM_FILM_CHANNELS_HAS_DEPTH)\n"
"		sampleResult->depth = INFINITY;\n"
"#endif\n"
"#if defined(PARAM_FILM_CHANNELS_HAS_POSITION)\n"
"		sampleResult->position.x = INFINITY;\n"
"		sampleResult->position.y = INFINITY;\n"
"		sampleResult->position.z = INFINITY;\n"
"#endif\n"
"#if defined(PARAM_FILM_CHANNELS_HAS_GEOMETRY_NORMAL)\n"
"		sampleResult->geometryNormal.x = INFINITY;\n"
"		sampleResult->geometryNormal.y = INFINITY;\n"
"		sampleResult->geometryNormal.z = INFINITY;\n"
"#endif\n"
"#if defined(PARAM_FILM_CHANNELS_HAS_SHADING_NORMAL)\n"
"		sampleResult->shadingNormal.x = INFINITY;\n"
"		sampleResult->shadingNormal.y = INFINITY;\n"
"		sampleResult->shadingNormal.z = INFINITY;\n"
"#endif\n"
"#if defined(PARAM_FILM_CHANNELS_HAS_MATERIAL_ID)\n"
"		sampleResult->materialID = NULL_INDEX;\n"
"#endif\n"
"#if defined(PARAM_FILM_CHANNELS_HAS_UV)\n"
"		sampleResult->uv.u = INFINITY;\n"
"		sampleResult->uv.v = INFINITY;\n"
"#endif\n"
"	}\n"
"\n"
"	//--------------------------------------------------------------------------\n"
"	// Save the result\n"
"	//--------------------------------------------------------------------------\n"
"\n"
"#if defined(PARAM_FILM_CHANNELS_HAS_RAYCOUNT)\n"
"	sampleResult->rayCount = tracedRaysCount;\n"
"#endif\n"
"\n"
"	taskStat->raysCount = tracedRaysCount;\n"
"\n"
"	// Save the seed\n"
"	task->seed.s1 = seed.s1;\n"
"	task->seed.s2 = seed.s2;\n"
"	task->seed.s3 = seed.s3;\n"
"}\n"
; } }
