#include <string>
namespace slg { namespace ocl {
std::string KernelSource_film_types = 
"#line 2 \"film_types.cl\"\n"
"\n"
"/***************************************************************************\n"
" *   Copyright (C) 1998-2013 by authors (see AUTHORS.txt)                  *\n"
" *                                                                         *\n"
" *   This file is part of LuxRays.                                         *\n"
" *                                                                         *\n"
" *   LuxRays is free software; you can redistribute it and/or modify       *\n"
" *   it under the terms of the GNU General Public License as published by  *\n"
" *   the Free Software Foundation; either version 3 of the License, or     *\n"
" *   (at your option) any later version.                                   *\n"
" *                                                                         *\n"
" *   LuxRays is distributed in the hope that it will be useful,            *\n"
" *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *\n"
" *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *\n"
" *   GNU General Public License for more details.                          *\n"
" *                                                                         *\n"
" *   You should have received a copy of the GNU General Public License     *\n"
" *   along with this program.  If not, see <http://www.gnu.org/licenses/>. *\n"
" *                                                                         *\n"
" *   LuxRays website: http://www.luxrender.net                             *\n"
" ***************************************************************************/\n"
"\n"
"//------------------------------------------------------------------------------\n"
"// SampleResult\n"
"//------------------------------------------------------------------------------\n"
"\n"
"#if defined(SLG_OPENCL_KERNEL)\n"
"\n"
"typedef struct {\n"
"	float filmX, filmY;\n"
"	Spectrum radiancePerPixelNormalized[PARAM_FILM_RADIANCE_GROUP_COUNT];\n"
"#if defined(PARAM_FILM_CHANNELS_HAS_ALPHA)\n"
"	float alpha;\n"
"#endif\n"
"#if defined(PARAM_FILM_CHANNELS_HAS_DEPTH)\n"
"	float depth;\n"
"#endif\n"
"#if defined(PARAM_FILM_CHANNELS_HAS_POSITION)\n"
"	Point position;\n"
"#endif\n"
"#if defined(PARAM_FILM_CHANNELS_HAS_GEOMETRY_NORMAL)\n"
"	Normal geometryNormal;\n"
"#endif\n"
"#if defined(PARAM_FILM_CHANNELS_HAS_SHADING_NORMAL)\n"
"	Normal shadingNormal;\n"
"#endif\n"
"#if defined(PARAM_FILM_CHANNELS_HAS_MATERIAL_ID)\n"
"	// Note: MATERIAL_ID_MASK is calculated starting from materialID field\n"
"	uint materialID;\n"
"#endif\n"
"#if defined(PARAM_FILM_CHANNELS_HAS_DIRECT_DIFFUSE)\n"
"	Spectrum directDiffuse;\n"
"#endif\n"
"#if defined(PARAM_FILM_CHANNELS_HAS_DIRECT_GLOSSY)\n"
"	Spectrum directGlossy;\n"
"#endif\n"
"#if defined(PARAM_FILM_CHANNELS_HAS_EMISSION)\n"
"	Spectrum emission;\n"
"#endif\n"
"#if defined(PARAM_FILM_CHANNELS_HAS_INDIRECT_DIFFUSE)\n"
"	Spectrum indirectDiffuse;\n"
"#endif\n"
"#if defined(PARAM_FILM_CHANNELS_HAS_INDIRECT_GLOSSY)\n"
"	Spectrum indirectGlossy;\n"
"#endif\n"
"#if defined(PARAM_FILM_CHANNELS_HAS_INDIRECT_SPECULAR)\n"
"	Spectrum indirectSpecular;\n"
"#endif\n"
"#if defined(PARAM_FILM_CHANNELS_HAS_DIRECT_SHADOW_MASK)\n"
"	float directShadowMask;\n"
"#endif\n"
"#if defined(PARAM_FILM_CHANNELS_HAS_INDIRECT_SHADOW_MASK)\n"
"	float indirectShadowMask;\n"
"#endif\n"
"#if defined(PARAM_FILM_CHANNELS_HAS_UV)\n"
"	UV uv;\n"
"#endif\n"
"} SampleResult;\n"
"\n"
"#endif\n"
"\n"
"//------------------------------------------------------------------------------\n"
"// Some macro trick in order to have more readable code\n"
"//------------------------------------------------------------------------------\n"
"\n"
"#if defined(SLG_OPENCL_KERNEL)\n"
"\n"
"#define FILM_RADIANCE_GROUP_PARAM_DECL , __global float **filmRadianceGroup\n"
"#define FILM_RADIANCE_GROUP_PARAM , filmRadianceGroup\n"
"\n"
"#if defined(PARAM_FILM_CHANNELS_HAS_ALPHA)\n"
"#define FILM_ALPHA_PARAM_DECL , __global float *filmAlpha\n"
"#define FILM_ALPHA_PARAM , filmAlpha\n"
"#else\n"
"#define FILM_ALPHA_PARAM_DECL\n"
"#define FILM_ALPHA_PARAM\n"
"#endif\n"
"#if defined(PARAM_FILM_CHANNELS_HAS_DEPTH)\n"
"#define FILM_DEPTH_PARAM_DECL , __global float *filmDepth\n"
"#define FILM_DEPTH_PARAM , filmDepth\n"
"#else\n"
"#define FILM_DEPTH_PARAM_DECL\n"
"#define FILM_DEPTH_PARAM\n"
"#endif\n"
"#if defined(PARAM_FILM_CHANNELS_HAS_POSITION)\n"
"#define FILM_POSITION_PARAM_DECL , __global float *filmPosition\n"
"#define FILM_POSITION_PARAM , filmPosition\n"
"#else\n"
"#define FILM_POSITION_PARAM_DECL\n"
"#define FILM_POSITION_PARAM\n"
"#endif\n"
"#if defined(PARAM_FILM_CHANNELS_HAS_GEOMETRY_NORMAL)\n"
"#define FILM_GEOMETRY_NORMAL_PARAM_DECL , __global float *filmGeometryNormal\n"
"#define FILM_GEOMETRY_NORMAL_PARAM , filmGeometryNormal\n"
"#else\n"
"#define FILM_GEOMETRY_NORMAL_PARAM_DECL\n"
"#define FILM_GEOMETRY_NORMAL_PARAM\n"
"#endif\n"
"#if defined(PARAM_FILM_CHANNELS_HAS_SHADING_NORMAL)\n"
"#define FILM_SHADING_NORMAL_PARAM_DECL , __global float *filmShadingNormal\n"
"#define FILM_SHADING_NORMAL_PARAM , filmShadingNormal\n"
"#else\n"
"#define FILM_SHADING_NORMAL_PARAM_DECL\n"
"#define FILM_SHADING_NORMAL_PARAM\n"
"#endif\n"
"#if defined(PARAM_FILM_CHANNELS_HAS_MATERIAL_ID)\n"
"#define FILM_MATERIAL_ID_PARAM_DECL , __global uint *filmMaterialID\n"
"#define FILM_MATERIAL_ID_PARAM , filmMaterialID\n"
"#else\n"
"#define FILM_MATERIAL_ID_PARAM_DECL\n"
"#define FILM_MATERIAL_ID_PARAM\n"
"#endif\n"
"#if defined(PARAM_FILM_CHANNELS_HAS_DIRECT_DIFFUSE)\n"
"#define FILM_DIRECT_DIFFUSE_PARAM_DECL , __global float *filmDirectDiffuse\n"
"#define FILM_DIRECT_DIFFUSE_PARAM , filmDirectDiffuse\n"
"#else\n"
"#define FILM_DIRECT_DIFFUSE_PARAM_DECL\n"
"#define FILM_DIRECT_DIFFUSE_PARAM\n"
"#endif\n"
"#if defined(PARAM_FILM_CHANNELS_HAS_DIRECT_GLOSSY)\n"
"#define FILM_DIRECT_GLOSSY_PARAM_DECL , __global float *filmDirectGlossy\n"
"#define FILM_DIRECT_GLOSSY_PARAM , filmDirectGlossy\n"
"#else\n"
"#define FILM_DIRECT_GLOSSY_PARAM_DECL\n"
"#define FILM_DIRECT_GLOSSY_PARAM\n"
"#endif\n"
"#if defined(PARAM_FILM_CHANNELS_HAS_EMISSION)\n"
"#define FILM_EMISSION_PARAM_DECL , __global float *filmEmission\n"
"#define FILM_EMISSION_PARAM , filmEmission\n"
"#else\n"
"#define FILM_EMISSION_PARAM_DECL\n"
"#define FILM_EMISSION_PARAM\n"
"#endif\n"
"#if defined(PARAM_FILM_CHANNELS_HAS_INDIRECT_DIFFUSE)\n"
"#define FILM_INDIRECT_DIFFUSE_PARAM_DECL , __global float *filmIndirectDiffuse\n"
"#define FILM_INDIRECT_DIFFUSE_PARAM , filmIndirectDiffuse\n"
"#else\n"
"#define FILM_INDIRECT_DIFFUSE_PARAM_DECL\n"
"#define FILM_INDIRECT_DIFFUSE_PARAM\n"
"#endif\n"
"#if defined(PARAM_FILM_CHANNELS_HAS_INDIRECT_GLOSSY)\n"
"#define FILM_INDIRECT_GLOSSY_PARAM_DECL , __global float *filmIndirectGlossy\n"
"#define FILM_INDIRECT_GLOSSY_PARAM , filmIndirectGlossy\n"
"#else\n"
"#define FILM_INDIRECT_GLOSSY_PARAM_DECL\n"
"#define FILM_INDIRECT_GLOSSY_PARAM\n"
"#endif\n"
"#if defined(PARAM_FILM_CHANNELS_HAS_INDIRECT_SPECULAR)\n"
"#define FILM_INDIRECT_SPECULAR_PARAM_DECL , __global float *filmIndirectSpecular\n"
"#define FILM_INDIRECT_SPECULAR_PARAM , filmIndirectSpecular\n"
"#else\n"
"#define FILM_INDIRECT_SPECULAR_PARAM_DECL\n"
"#define FILM_INDIRECT_SPECULAR_PARAM\n"
"#endif\n"
"#if defined(PARAM_FILM_CHANNELS_HAS_MATERIAL_ID_MASK)\n"
"#define FILM_MATERIAL_ID_MASK_PARAM_DECL , __global float *filmMaterialIDMask\n"
"#define FILM_MATERIAL_ID_MASK_PARAM , filmMaterialIDMask\n"
"#else\n"
"#define FILM_MATERIAL_ID_MASK_PARAM_DECL\n"
"#define FILM_MATERIAL_ID_MASK_PARAM\n"
"#endif\n"
"#if defined(PARAM_FILM_CHANNELS_HAS_DIRECT_SHADOW_MASK)\n"
"#define FILM_DIRECT_SHADOW_MASK_PARAM_DECL , __global float *filmDirectShadowMask\n"
"#define FILM_DIRECT_SHADOW_MASK_PARAM , filmDirectShadowMask\n"
"#else\n"
"#define FILM_DIRECT_SHADOW_MASK_PARAM_DECL\n"
"#define FILM_DIRECT_SHADOW_MASK_PARAM\n"
"#endif\n"
"#if defined(PARAM_FILM_CHANNELS_HAS_INDIRECT_SHADOW_MASK)\n"
"#define FILM_INDIRECT_SHADOW_MASK_PARAM_DECL , __global float *filmIndirectShadowMask\n"
"#define FILM_INDIRECT_SHADOW_MASK_PARAM , filmIndirectShadowMask\n"
"#else\n"
"#define FILM_INDIRECT_SHADOW_MASK_PARAM_DECL\n"
"#define FILM_INDIRECT_SHADOW_MASK_PARAM\n"
"#endif\n"
"#if defined(PARAM_FILM_CHANNELS_HAS_UV)\n"
"#define FILM_UV_PARAM_DECL , __global float *filmUV\n"
"#define FILM_UV_PARAM , filmUV\n"
"#else\n"
"#define FILM_UV_PARAM_DECL\n"
"#define FILM_UV_PARAM\n"
"#endif\n"
"\n"
"#define FILM_PARAM_DECL , const uint filmWidth, const uint filmHeight FILM_RADIANCE_GROUP_PARAM_DECL FILM_ALPHA_PARAM_DECL FILM_DEPTH_PARAM_DECL FILM_POSITION_PARAM_DECL FILM_GEOMETRY_NORMAL_PARAM_DECL FILM_SHADING_NORMAL_PARAM_DECL FILM_MATERIAL_ID_PARAM_DECL FILM_DIRECT_DIFFUSE_PARAM_DECL FILM_DIRECT_GLOSSY_PARAM_DECL FILM_EMISSION_PARAM_DECL FILM_INDIRECT_DIFFUSE_PARAM_DECL FILM_INDIRECT_GLOSSY_PARAM_DECL FILM_INDIRECT_SPECULAR_PARAM_DECL FILM_MATERIAL_ID_MASK_PARAM_DECL FILM_DIRECT_SHADOW_MASK_PARAM_DECL FILM_INDIRECT_SHADOW_MASK_PARAM_DECL FILM_UV_PARAM_DECL\n"
"#define FILM_PARAM , filmWidth, filmHeight FILM_RADIANCE_GROUP_PARAM FILM_ALPHA_PARAM FILM_DEPTH_PARAM FILM_POSITION_PARAM FILM_GEOMETRY_NORMAL_PARAM FILM_SHADING_NORMAL_PARAM FILM_MATERIAL_ID_PARAM FILM_DIRECT_DIFFUSE_PARAM FILM_DIRECT_GLOSSY_PARAM FILM_EMISSION_PARAM FILM_INDIRECT_DIFFUSE_PARAM FILM_INDIRECT_GLOSSY_PARAM FILM_INDIRECT_SPECULAR_PARAM FILM_MATERIAL_ID_MASK_PARAM FILM_DIRECT_SHADOW_MASK_PARAM FILM_INDIRECT_SHADOW_MASK_PARAM FILM_UV_PARAM\n"
"\n"
"#endif\n"
; } }
