#include <string>
namespace slg { namespace ocl {
std::string KernelSource_light_types = 
"#line 2 \"light_types.cl\"\n"
"\n"
"/***************************************************************************\n"
" * Copyright 1998-2013 by authors (see AUTHORS.txt)                        *\n"
" *                                                                         *\n"
" *   This file is part of LuxRender.                                       *\n"
" *                                                                         *\n"
" * Licensed under the Apache License, Version 2.0 (the \"License\");         *\n"
" * you may not use this file except in compliance with the License.        *\n"
" * You may obtain a copy of the License at                                 *\n"
" *                                                                         *\n"
" *     http://www.apache.org/licenses/LICENSE-2.0                          *\n"
" *                                                                         *\n"
" * Unless required by applicable law or agreed to in writing, software     *\n"
" * distributed under the License is distributed on an \"AS IS\" BASIS,       *\n"
" * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.*\n"
" * See the License for the specific language governing permissions and     *\n"
" * limitations under the License.                                          *\n"
" ***************************************************************************/\n"
"\n"
"typedef enum {\n"
"	TYPE_IL, TYPE_IL_SKY, TYPE_SUN, TYPE_TRIANGLE\n"
"} LightSourceType;\n"
"\n"
"typedef struct {\n"
"	Transform light2World;\n"
"	Spectrum gain;\n"
"	TextureMapping2D mapping;\n"
"	unsigned int imageMapIndex;\n"
"	unsigned int lightSceneIndex, lightID;\n"
"} InfiniteLight;\n"
"\n"
"typedef struct {\n"
"	Transform light2World;\n"
"	Spectrum gain;\n"
"	float thetaS;\n"
"	float phiS;\n"
"	float zenith_Y, zenith_x, zenith_y;\n"
"	float perez_Y[6], perez_x[6], perez_y[6];\n"
"	unsigned int lightSceneIndex, lightID;\n"
"} SkyLight;\n"
"\n"
"typedef struct {\n"
"	Vector sunDir;\n"
"	Spectrum gain;\n"
"	float turbidity;\n"
"	float relSize;\n"
"	// XY Vectors for cone sampling\n"
"	Vector x, y;\n"
"	float cosThetaMax;\n"
"	Spectrum sunColor;\n"
"	unsigned int lightSceneIndex, lightID;\n"
"} SunLight;\n"
"\n"
"typedef struct {\n"
"	Vector v0, v1, v2;\n"
"	UV uv0, uv1, uv2;\n"
"	float invArea;\n"
"\n"
"	unsigned int materialIndex;\n"
"	unsigned int lightSceneIndex;\n"
"} TriangleLight;\n"
; } }
