#include <string>
namespace slg { namespace ocl {
std::string KernelSource_materialdefs_funcs_glass = 
"#line 2 \"materialdefs_funcs_glass.cl\"\n"
"\n"
"/***************************************************************************\n"
" * Copyright 1998-2018 by authors (see AUTHORS.txt)                        *\n"
" *                                                                         *\n"
" *   This file is part of LuxCoreRender.                                   *\n"
" *                                                                         *\n"
" * Licensed under the Apache License, Version 2.0 (the \"License\");         *\n"
" * you may not use this file except in compliance with the License.        *\n"
" * You may obtain a copy of the License at                                 *\n"
" *                                                                         *\n"
" *     http://www.apache.org/licenses/LICENSE-2.0                          *\n"
" *                                                                         *\n"
" * Unless required by applicable law or agreed to in writing, software     *\n"
" * distributed under the License is distributed on an \"AS IS\" BASIS,       *\n"
" * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.*\n"
" * See the License for the specific language governing permissions and     *\n"
" * limitations under the License.                                          *\n"
" ***************************************************************************/\n"
"\n"
"//------------------------------------------------------------------------------\n"
"// Glass material\n"
"//------------------------------------------------------------------------------\n"
"\n"
"#if defined (PARAM_ENABLE_MAT_GLASS)\n"
"\n"
"BSDFEvent GlassMaterial_GetEventTypes() {\n"
"	return SPECULAR | REFLECT | TRANSMIT;\n"
"}\n"
"\n"
"bool GlassMaterial_IsDelta() {\n"
"	return true;\n"
"}\n"
"\n"
"float3 GlassMaterial_Evaluate(\n"
"		__global HitPoint *hitPoint, const float3 lightDir, const float3 eyeDir,\n"
"		BSDFEvent *event, float *directPdfW,\n"
"		const float3 ktTexVal, const float3 krTexVal,\n"
"		const float3 nc, const float3 nt, const bool dispersion) {\n"
"	return BLACK;\n"
"}\n"
"\n"
"float3 GlassMaterial_WaveLength2RGB(const float waveLength) {\n"
"	float r, g, b;\n"
"	if ((waveLength >= 380.f) && (waveLength < 440.f)) {\n"
"		r = -(waveLength - 440.f) / (440 - 380.f);\n"
"		g = 0.f;\n"
"		b = 1.f;\n"
"	} else if ((waveLength >= 440.f) && (waveLength < 490.f)) {\n"
"		r = 0.f;\n"
"		g = (waveLength - 440.f) / (490.f - 440.f);\n"
"		b = 1.f;\n"
"	} else if ((waveLength >= 490.f) && (waveLength < 510.f)) {\n"
"		r = 0.f;\n"
"		g = 1.f;\n"
"		b = -(waveLength - 510.f) / (510.f - 490.f);\n"
"	} else if ((waveLength >= 510.f) && (waveLength < 580.f)) {\n"
"		r = (waveLength - 510.f) / (580.f - 510.f);\n"
"		g = 1.f;\n"
"		b = 0.f;\n"
"	} else if ((waveLength >= 580.f) && (waveLength < 645.f)) {\n"
"		r = 1.f;\n"
"		g = -(waveLength - 645.f) / (645 - 580.f);\n"
"		b = 0.f;\n"
"	} else if ((waveLength >= 645.f) && (waveLength < 780.f)) {\n"
"		r = 1.f;\n"
"		g = 0.f;\n"
"		b = 0.f;\n"
"	} else\n"
"		return BLACK;\n"
"\n"
"	// The intensity fall off near the upper and lower limits\n"
"	float factor;\n"
"	if ((waveLength >= 380.f) && (waveLength < 420.f))\n"
"		factor = .3f + .7f * (waveLength - 380.f) / (420.f - 380.f);\n"
"	else if ((waveLength >= 420) && (waveLength < 700))\n"
"		factor = 1.f;\n"
"	else\n"
"		factor = .3f + .7f * (780.f - waveLength) / (780.f - 700.f);\n"
"\n"
"	const float3 result = (float3)(r, g, b) * factor;\n"
"\n"
"	/*\n"
"	Spectrum white;\n"
"	for (u_int i = 380; i < 780; ++i)\n"
"		white += WaveLength2RGB(i);\n"
"	white *= 1.f / 400.f;\n"
"	cout << std::setprecision(std::numeric_limits<float>::digits10 + 1) << white.c[0] << \", \" << white.c[1] << \", \" << white.c[2] << \"\\n\";\n"
"	 \n"
"	 Result: 0.5652729, 0.36875, 0.265375\n"
"	 */\n"
"\n"
"	// To normalize the output\n"
"	const float3 normFactor = (float3)(1.f / .5652729f, 1.f / .36875f, 1.f / .265375f);\n"
"	\n"
"	return result * normFactor;\n"
"}\n"
"\n"
"float GlassMaterial_WaveLength2IOR(const float waveLength, const float3 IORs) {\n"
"	// Using Lagrange Interpolating Polynomial to interpolate IOR values\n"
"	//\n"
"	// The used points are (440, B), (510, G), (645, R)\n"
"	// Lagrange Interpolating Polynomial:\n"
"	//  f(x) =\n"
"	//    y1 * ((x - x2)(x - x3)) / ((x1 - x2)(x1 - x3)) +\n"
"	//    y2 * ((x - x1)(x - x3)) / ((x2 - x1)(x2 - x3)) +\n"
"	//    y3 * ((x - x1)(x - x2)) / ((x3 - x1)(x3 - x2))\n"
"\n"
"	const float x1 = 440.f;\n"
"	const float y1 = IORs.s2;\n"
"	const float x2 = 510.f;\n"
"	const float y2 = IORs.s1;\n"
"	const float x3 = 645.f;\n"
"	const float y3 = IORs.s0;\n"
"	\n"
"	const float fx =\n"
"		y1 * ((waveLength - x2) * (waveLength - x3)) / ((x1 - x2) * (x1 - x3)) +\n"
"		y2 * ((waveLength - x1) * (waveLength - x3)) / ((x2 - x1) * (x2 - x3)) +\n"
"		y3 * ((waveLength - x1) * (waveLength - x2)) / ((x3 - x1) * (x3 - x2));\n"
"	\n"
"	return fx;\n"
"}\n"
"\n"
"float3 GlassMaterial_Sample(\n"
"		__global HitPoint *hitPoint, const float3 localFixedDir, float3 *localSampledDir,\n"
"		const float u0, const float u1,\n"
"#if defined(PARAM_HAS_PASSTHROUGH)\n"
"		const float passThroughEvent,\n"
"#endif\n"
"		float *pdfW, float *absCosSampledDir, BSDFEvent *event,\n"
"		const BSDFEvent requestedEvent,\n"
"		const float3 ktTexVal, const float3 krTexVal,\n"
"		const float3 nc, const float3 nt, const bool dispersion) {\n"
"	if (!(requestedEvent & SPECULAR))\n"
"		return BLACK;\n"
"\n"
"	const float3 kt = Spectrum_Clamp(ktTexVal);\n"
"	const float3 kr = Spectrum_Clamp(krTexVal);\n"
"\n"
"	const bool isKtBlack = Spectrum_IsBlack(kt);\n"
"	const bool isKrBlack = Spectrum_IsBlack(kr);\n"
"	if (isKtBlack && isKrBlack)\n"
"		return BLACK;\n"
"\n"
"	const bool entering = (CosTheta(localFixedDir) > 0.f);\n"
"	const float costheta = CosTheta(localFixedDir);\n"
"\n"
"	// Decide to transmit or reflect\n"
"	float threshold;\n"
"	if ((requestedEvent & REFLECT) && !isKrBlack) {\n"
"		if ((requestedEvent & TRANSMIT) && !isKtBlack)\n"
"			threshold = .5f;\n"
"		else\n"
"			threshold = 0.f;\n"
"	} else {\n"
"		if ((requestedEvent & TRANSMIT) && !isKtBlack)\n"
"			threshold = 1.f;\n"
"		else\n"
"			return BLACK;\n"
"	}\n"
"\n"
"	float3 result;\n"
"	if (passThroughEvent < threshold) {\n"
"		// Transmit\n"
"	\n"
"		// Compute transmitted ray direction\n"
"		const float sini2 = SinTheta2(localFixedDir);\n"
"		\n"
"		float3 lkt;\n"
"		float lnc, lnt;\n"
"		if (dispersion) {\n"
"			// Select the wavelength to sample\n"
"			const float waveLength = mix(380.f, 780.f, u0);\n"
"\n"
"			lnc = GlassMaterial_WaveLength2IOR(waveLength, nc);\n"
"			lnt = GlassMaterial_WaveLength2IOR(waveLength, nt);\n"
"\n"
"			lkt = kt * GlassMaterial_WaveLength2RGB(waveLength);\n"
"		} else {\n"
"			lnc = Spectrum_Filter(nc);\n"
"			lnt = Spectrum_Filter(nt);\n"
"			lkt = kt;\n"
"		}\n"
"\n"
"		const float ntc = lnt / lnc;\n"
"		const float eta = entering ? (lnc / lnt) : ntc;\n"
"		const float eta2 = eta * eta;\n"
"		const float sint2 = eta2 * sini2;\n"
"		\n"
"		// Handle total internal reflection for transmission\n"
"		if (sint2 >= 1.f)\n"
"			return BLACK;\n"
"\n"
"		const float cost = sqrt(fmax(0.f, 1.f - sint2)) * (entering ? -1.f : 1.f);\n"
"		*localSampledDir = (float3)(-eta * localFixedDir.x, -eta * localFixedDir.y, cost);\n"
"		*absCosSampledDir = fabs(CosTheta(*localSampledDir));\n"
"\n"
"		*event = SPECULAR | TRANSMIT;\n"
"		*pdfW = threshold;\n"
"\n"
"		float ce;\n"
"		//if (!hitPoint.fromLight)\n"
"			ce = (1.f - FresnelCauchy_Evaluate(ntc, cost)) * eta2;\n"
"		//else\n"
"		//	ce = (1.f - FresnelCauchy_Evaluate(ntc, costheta));\n"
"\n"
"		result = lkt * ce;\n"
"	} else {\n"
"		// Reflect\n"
"		\n"
"		*localSampledDir = (float3)(-localFixedDir.x, -localFixedDir.y, localFixedDir.z);\n"
"		*absCosSampledDir = fabs(CosTheta(*localSampledDir));\n"
"\n"
"		*event = SPECULAR | REFLECT;\n"
"		*pdfW = 1.f - threshold;\n"
"\n"
"		if (dispersion) {\n"
"			const float3 ntc = nt / nc;\n"
"			result.s0 = kr.s0 * FresnelCauchy_Evaluate(ntc.s0, costheta);\n"
"			result.s1 = kr.s1 * FresnelCauchy_Evaluate(ntc.s1, costheta);\n"
"			result.s2 = kr.s2 * FresnelCauchy_Evaluate(ntc.s2, costheta);\n"
"		} else {\n"
"			const float ntc = Spectrum_Filter(nt) / Spectrum_Filter(nc);\n"
"			result = kr * FresnelCauchy_Evaluate(ntc, costheta);\n"
"		}\n"
"	}\n"
"\n"
"	return result / *pdfW;\n"
"}\n"
"\n"
"#endif\n"
; } }
