#include <string>
namespace slg { namespace ocl {
std::string KernelSource_texture_blender_funcs = 
"#line 2 \"texture_blender_funcs.cl\"\n"
"\n"
"/***************************************************************************\n"
" * Copyright 1998-2013 by authors (see AUTHORS.txt)                        *\n"
" *                                                                         *\n"
" *   This file is part of LuxRender.                                       *\n"
" *                                                                         *\n"
" * Licensed under the Apache License, Version 2.0 (the \"License\");         *\n"
" * you may not use this file except in compliance with the License.        *\n"
" * You may obtain a copy of the License at                                 *\n"
" *                                                                         *\n"
" *     http://www.apache.org/licenses/LICENSE-2.0                          *\n"
" *                                                                         *\n"
" * Unless required by applicable law or agreed to in writing, software     *\n"
" * distributed under the License is distributed on an \"AS IS\" BASIS,       *\n"
" * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.*\n"
" * See the License for the specific language governing permissions and     *\n"
" * limitations under the License.                                          *\n"
" ***************************************************************************/\n"
"\n"
"#ifndef TEXTURE_STACK_SIZE\n"
"#define TEXTURE_STACK_SIZE 16\n"
"#endif\n"
"\n"
"//------------------------------------------------------------------------------\n"
"// Blender wood texture\n"
"//------------------------------------------------------------------------------\n"
"\n"
"#if defined(PARAM_ENABLE_BLENDER_WOOD)\n"
"\n"
"float BlenderWoodTexture_Evaluate(__global HitPoint *hitPoint,\n"
"		const BlenderWoodType type, const BlenderWoodNoiseBase noisebasis2,\n"
"		const float noisesize, const float turbulence,\n"
"		const float contrast, const float bright, const bool hard,\n"
"		__global TextureMapping3D *mapping) {\n"
"	const float3 P = TextureMapping3D_Map(mapping, hitPoint);\n"
"	float scale = 1.f;\n"
"	if (fabs(noisesize) > 0.00001f) scale = (1.f / noisesize);\n"
"\n"
"	float wood = 0.f;\n"
"	switch(type) {\n"
"		default:\n"
"		case BANDS:\n"
"			if(noisebasis2 == TEX_SIN) {\n"
"				wood = tex_sin((P.x + P.y + P.z) * 10.f);\n"
"			} else if(noisebasis2 == TEX_SAW) {\n"
"				wood = tex_saw((P.x + P.y + P.z) * 10.f);\n"
"			} else {\n"
"				wood = tex_tri((P.x + P.y + P.z) * 10.f);\n"
"			}\n"
"			break;\n"
"		case RINGS:\n"
"			if(noisebasis2 == TEX_SIN) {\n"
"				wood = tex_sin(sqrt(P.x*P.x + P.y*P.y + P.z*P.z) * 20.f);\n"
"			} else if(noisebasis2 == TEX_SAW) {\n"
"				wood = tex_saw(sqrt(P.x*P.x + P.y*P.y + P.z*P.z) * 20.f);\n"
"			} else {\n"
"				wood = tex_tri(sqrt(P.x*P.x + P.y*P.y + P.z*P.z) * 20.f);\n"
"			}\n"
"			break;\n"
"		case BANDNOISE:			\n"
"			if(hard)	\n"
"				wood = turbulence * fabs(2.f * Noise3(scale*P) - 1.f);\n"
"			else\n"
"				wood = turbulence * Noise3(scale*P);\n"
"\n"
"			if(noisebasis2 == TEX_SIN) {\n"
"				wood = tex_sin((P.x + P.y + P.z) * 10.f + wood);\n"
"			} else if(noisebasis2 == TEX_SAW) {\n"
"				wood = tex_saw((P.x + P.y + P.z) * 10.f + wood);\n"
"			} else {\n"
"				wood = tex_tri((P.x + P.y + P.z) * 10.f + wood);\n"
"			}\n"
"			break;\n"
"		case RINGNOISE:\n"
"			if(hard)	\n"
"				wood = turbulence * fabs(2.f * Noise3(scale*P) - 1.f);\n"
"			else\n"
"				wood = turbulence * Noise3(scale*P);\n"
"\n"
"			if(noisebasis2 == TEX_SIN) {\n"
"				wood = tex_sin(sqrt(P.x*P.x + P.y*P.y + P.z*P.z) * 20.f + wood);\n"
"			} else if(noisebasis2 == TEX_SAW) {\n"
"				wood = tex_saw(sqrt(P.x*P.x + P.y*P.y + P.z*P.z) * 20.f + wood);\n"
"			} else {\n"
"				wood = tex_tri(sqrt(P.x*P.x + P.y*P.y + P.z*P.z) * 20.f + wood);\n"
"			}\n"
"			break;\n"
"	}\n"
"	wood = (wood - 0.5f) * contrast + bright - 0.5f;\n"
"	wood = clamp(wood, 0.f, 1.f);\n"
"\n"
"	return wood;\n"
"}\n"
"\n"
"float BlenderWoodTexture_ConstEvaluateFloat(__global HitPoint *hitPoint,\n"
"		const BlenderWoodType type, const BlenderWoodNoiseBase noisebasis2,\n"
"		const float noisesize, const float turbulence,\n"
"		const float contrast, const float bright, const bool hard,\n"
"		__global TextureMapping3D *mapping) {\n"
"	return BlenderWoodTexture_Evaluate(hitPoint, type, noisebasis2,\n"
"		noisesize, turbulence, contrast, bright, hard, mapping);\n"
"}\n"
"\n"
"float3 BlenderWoodTexture_ConstEvaluateSpectrum(__global HitPoint *hitPoint,\n"
"		const BlenderWoodType type, const BlenderWoodNoiseBase noisebasis2,\n"
"		const float noisesize, const float turbulence,\n"
"		const float contrast, const float bright, const bool hard,\n"
"		__global TextureMapping3D *mapping) {\n"
"    return BlenderWoodTexture_Evaluate(hitPoint, type, noisebasis2,\n"
"		noisesize, turbulence, contrast, bright, hard, mapping);\n"
"}\n"
"\n"
"#if defined(PARAM_DIASBLE_TEX_DYNAMIC_EVALUATION)\n"
"void BlenderWoodTexture_EvaluateFloat(__global Texture *texture, __global HitPoint *hitPoint,\n"
"		float texValues[TEXTURE_STACK_SIZE], uint *texValuesSize) {\n"
"	texValues[(*texValuesSize)++] = BlenderWoodTexture_ConstEvaluateFloat(hitPoint,\n"
"			texture->blenderWood.type, texture->blenderWood.noisebasis2,\n"
"			texture->blenderWood.noisesize, texture->blenderWood.turbulence, \n"
"			texture->blenderWood.contrast, texture->blenderWood.bright,\n"
"			texture->blenderWood.hard, &texture->blenderWood.mapping);\n"
"}\n"
"\n"
"void BlenderWoodTexture_EvaluateSpectrum(__global Texture *texture, __global HitPoint *hitPoint,\n"
"	float3 texValues[TEXTURE_STACK_SIZE], uint *texValuesSize) {\n"
"    texValues[(*texValuesSize)++] = BlenderWoodTexture_ConstEvaluateSpectrum(hitPoint,\n"
"			texture->blenderWood.type, texture->blenderWood.noisebasis2,\n"
"			texture->blenderWood.noisesize, texture->blenderWood.turbulence, \n"
"			texture->blenderWood.contrast, texture->blenderWood.bright,\n"
"			texture->blenderWood.hard, &texture->blenderWood.mapping);\n"
"}\n"
"#endif\n"
"\n"
"#endif\n"
"\n"
"//------------------------------------------------------------------------------\n"
"// Blender clouds texture\n"
"//------------------------------------------------------------------------------\n"
"\n"
"#if defined(PARAM_ENABLE_BLENDER_CLOUDS)\n"
"\n"
"float BlenderCloudsTexture_Evaluate(__global HitPoint *hitPoint,\n"
"		const float noisesize, const int noisedepth, const float contrast,\n"
"		const float bright, __global TextureMapping3D *mapping) {\n"
"	const float3 P = TextureMapping3D_Map(mapping, hitPoint);\n"
"\n"
"	float scale = 1.f;\n"
"	if (fabs(noisesize) > 0.00001f) scale = (1.f / noisesize);\n"
"\n"
"	float clouds = Turbulence(scale*P, noisesize, noisedepth);\n"
"\n"
"	clouds = (clouds - 0.5f) * contrast + bright - 0.5f;\n"
"	clouds = clamp(clouds, 0.f, 1.f);\n"
"\n"
"	return clouds;\n"
"}\n"
"\n"
"float BlenderCloudsTexture_ConstEvaluateFloat(__global HitPoint *hitPoint,\n"
"		const float noisesize, const int noisedepth, const float contrast,\n"
"		const float bright, __global TextureMapping3D *mapping) {\n"
"	return BlenderCloudsTexture_Evaluate(hitPoint, noisesize, noisedepth,\n"
"			contrast, bright, mapping);\n"
"}\n"
"\n"
"float3 BlenderCloudsTexture_ConstEvaluateSpectrum(__global HitPoint *hitPoint,\n"
"		const float noisesize, const int noisedepth, const float contrast,\n"
"		const float bright, __global TextureMapping3D *mapping) {\n"
"	return BlenderCloudsTexture_Evaluate(hitPoint, noisesize, noisedepth,\n"
"			contrast, bright, mapping);\n"
"}\n"
"\n"
"#if defined(PARAM_DIASBLE_TEX_DYNAMIC_EVALUATION)\n"
"void BlenderCloudsTexture_EvaluateFloat(__global Texture *texture, __global HitPoint *hitPoint,\n"
"		float texValues[TEXTURE_STACK_SIZE], uint *texValuesSize) {\n"
"	texValues[(*texValuesSize)++] = BlenderCloudsTexture_ConstEvaluateFloat(hitPoint,\n"
"			texture->blenderClouds.noisesize, texture->blenderClouds.noisedepth,\n"
"			texture->blenderClouds.contrast, texture->blenderClouds.bright,\n"
"			&texture->blenderClouds.mapping);\n"
"}\n"
"\n"
"void BlenderCloudsTexture_EvaluateSpectrum(__global Texture *texture, __global HitPoint *hitPoint,\n"
"		float3 texValues[TEXTURE_STACK_SIZE], uint *texValuesSize) {\n"
"	texValues[(*texValuesSize)++] = BlenderCloudsTexture_ConstEvaluateSpectrum(hitPoint,\n"
"			texture->blenderClouds.noisesize, texture->blenderClouds.noisedepth,\n"
"			texture->blenderClouds.contrast, texture->blenderClouds.bright,\n"
"			&texture->blenderClouds.mapping);\n"
"}\n"
"#endif\n"
"\n"
"#endif\n"
; } }
