#include <string>
namespace slg { namespace ocl {
std::string KernelSource_texture_fresnelconst_funcs = 
"#line 2 \"texture_fresnelconst.cl\"\n"
"\n"
"/***************************************************************************\n"
" * Copyright 1998-2015 by authors (see AUTHORS.txt)                        *\n"
" *                                                                         *\n"
" *   This file is part of LuxRender.                                       *\n"
" *                                                                         *\n"
" * Licensed under the Apache License, Version 2.0 (the \"License\");         *\n"
" * you may not use this file except in compliance with the License.        *\n"
" * You may obtain a copy of the License at                                 *\n"
" *                                                                         *\n"
" *     http://www.apache.org/licenses/LICENSE-2.0                          *\n"
" *                                                                         *\n"
" * Unless required by applicable law or agreed to in writing, software     *\n"
" * distributed under the License is distributed on an \"AS IS\" BASIS,       *\n"
" * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.*\n"
" * See the License for the specific language governing permissions and     *\n"
" * limitations under the License.                                          *\n"
" ***************************************************************************/\n"
"\n"
"//------------------------------------------------------------------------------\n"
"// FresnelConst texture\n"
"//------------------------------------------------------------------------------\n"
"\n"
"#if defined(PARAM_ENABLE_TEX_FRESNELCONST)\n"
"\n"
"// The following functions are never really used as Metal material has special\n"
"// code to evaluate Fresnel texture\n"
"\n"
"float FresnelConstTexture_ConstEvaluateFloat(__global const Texture *tex) {\n"
"	return 0.f;\n"
"}\n"
"\n"
"float3 FresnelConstTexture_ConstEvaluateSpectrum(__global const Texture *tex) {\n"
"	return 0.f;\n"
"}\n"
"\n"
"// Note: FresnelConstTexture_Bump() is defined in texture_bump_funcs.cl\n"
"\n"
"#endif\n"
; } }
