#include <string>
namespace slg { namespace ocl {
std::string KernelSource_volume_types = 
"#line 2 \"volume_types.cl\"\n"
"\n"
"/***************************************************************************\n"
" * Copyright 1998-2018 by authors (see AUTHORS.txt)                        *\n"
" *                                                                         *\n"
" *   This file is part of LuxCoreRender.                                   *\n"
" *                                                                         *\n"
" * Licensed under the Apache License, Version 2.0 (the \"License\");         *\n"
" * you may not use this file except in compliance with the License.        *\n"
" * You may obtain a copy of the License at                                 *\n"
" *                                                                         *\n"
" *     http://www.apache.org/licenses/LICENSE-2.0                          *\n"
" *                                                                         *\n"
" * Unless required by applicable law or agreed to in writing, software     *\n"
" * distributed under the License is distributed on an \"AS IS\" BASIS,       *\n"
" * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.*\n"
" * See the License for the specific language governing permissions and     *\n"
" * limitations under the License.                                          *\n"
" ***************************************************************************/\n"
"\n"
"// NOTE: check VolumeParam in material_type.cl for volume definitions\n"
"\n"
"#define OPENCL_PATHVOLUMEINFO_SIZE 8\n"
"\n"
"typedef struct {\n"
"	unsigned int currentVolumeIndex;\n"
"	unsigned int volumeIndexList[OPENCL_PATHVOLUMEINFO_SIZE];\n"
"	unsigned int volumeIndexListSize;\n"
"\n"
"	int scatteredStart;\n"
"} PathVolumeInfo;\n"
"\n"
"typedef Material Volume;\n"
; } }
