#include <string>
namespace luxrays { namespace ocl {
std::string KernelSource_filter_types = 
"#line 2 \"filter_types.cl\"\n"
"\n"
"/***************************************************************************\n"
" *   Copyright (C) 1998-2010 by authors (see AUTHORS.txt )                 *\n"
" *                                                                         *\n"
" *   This file is part of LuxRays.                                         *\n"
" *                                                                         *\n"
" *   LuxRays is free software; you can redistribute it and/or modify       *\n"
" *   it under the terms of the GNU General Public License as published by  *\n"
" *   the Free Software Foundation; either version 3 of the License, or     *\n"
" *   (at your option) any later version.                                   *\n"
" *                                                                         *\n"
" *   LuxRays is distributed in the hope that it will be useful,            *\n"
" *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *\n"
" *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *\n"
" *   GNU General Public License for more details.                          *\n"
" *                                                                         *\n"
" *   You should have received a copy of the GNU General Public License     *\n"
" *   along with this program.  If not, see <http://www.gnu.org/licenses/>. *\n"
" *                                                                         *\n"
" *   LuxRays website: http://www.luxrender.net                             *\n"
" ***************************************************************************/\n"
"\n"
"typedef enum {\n"
"	FILTER_NONE, FILTER_BOX, FILTER_GAUSSIAN, FILTER_MITCHELL\n"
"} FilterType;\n"
"\n"
"typedef struct {\n"
"	FilterType type;\n"
"	union {\n"
"		struct {\n"
"			float widthX, widthY;\n"
"		} box;\n"
"		struct {\n"
"			float widthX, widthY;\n"
"			float alpha;\n"
"		} gaussian;\n"
"		struct {\n"
"			float widthX, widthY;\n"
"			float B, C;\n"
"		} mitchell;\n"
"	};\n"
"} Filter;\n"
; } }
