#include "luxrays/kernels/kernels.h"
std::string luxrays::KernelSource_Pixel_ClearSampleFB = 
"/***************************************************************************\n"
" *   Copyright (C) 1998-2010 by authors (see AUTHORS.txt )                 *\n"
" *                                                                         *\n"
" *   This file is part of LuxRays.                                         *\n"
" *                                                                         *\n"
" *   LuxRays is free software; you can redistribute it and/or modify       *\n"
" *   it under the terms of the GNU General Public License as published by  *\n"
" *   the Free Software Foundation; either version 3 of the License, or     *\n"
" *   (at your option) any later version.                                   *\n"
" *                                                                         *\n"
" *   LuxRays is distributed in the hope that it will be useful,            *\n"
" *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *\n"
" *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *\n"
" *   GNU General Public License for more details.                          *\n"
" *                                                                         *\n"
" *   You should have received a copy of the GNU General Public License     *\n"
" *   along with this program.  If not, see <http://www.gnu.org/licenses/>. *\n"
" *                                                                         *\n"
" *   LuxRays website: http://www.luxrender.net                             *\n"
" ***************************************************************************/\n"
"\n"
"typedef struct {\n"
"	float r, g, b;\n"
"} Spectrum;\n"
"\n"
"typedef struct {\n"
"	Spectrum radiance;\n"
"	float weight;\n"
"} SamplePixel;\n"
"\n"
"__kernel void PixelClearSampleFB(__global SamplePixel *sampleFrameBuffer) {\n"
"	const unsigned int offset = get_global_id(0) + get_global_id(1) * get_global_size(0);\n"
"\n"
"	__global SamplePixel *sp = &sampleFrameBuffer[offset];\n"
"	sp->radiance.r = 0.f;\n"
"	sp->radiance.g = 0.f;\n"
"	sp->radiance.b = 0.f;\n"
"	sp->weight = 0.f;\n"
"}\n"
;
