#include <string>
namespace luxrays { namespace ocl {
std::string KernelSource_bbox_funcs = 
"#line 2 \"bbox_funcs.cl\"\n"
"\n"
"/***************************************************************************\n"
" * Copyright 1998-2018 by authors (see AUTHORS.txt)                        *\n"
" *                                                                         *\n"
" *   This file is part of LuxCoreRender.                                   *\n"
" *                                                                         *\n"
" * Licensed under the Apache License, Version 2.0 (the \"License\");         *\n"
" * you may not use this file except in compliance with the License.        *\n"
" * You may obtain a copy of the License at                                 *\n"
" *                                                                         *\n"
" *     http://www.apache.org/licenses/LICENSE-2.0                          *\n"
" *                                                                         *\n"
" * Unless required by applicable law or agreed to in writing, software     *\n"
" * distributed under the License is distributed on an \"AS IS\" BASIS,       *\n"
" * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.*\n"
" * See the License for the specific language governing permissions and     *\n"
" * limitations under the License.                                          *\n"
" ***************************************************************************/\n"
"\n"
"int BBox_IntersectP(const float3 pMin, const float3 pMax,\n"
"		const float3 rayOrig, const float3 invRayDir,\n"
"		const float mint, const float maxt) {\n"
"	const float3 l1 = (pMin - rayOrig) * invRayDir;\n"
"	const float3 l2 = (pMax - rayOrig) * invRayDir;\n"
"	const float3 tNear = fmin(l1, l2);\n"
"	const float3 tFar = fmax(l1, l2);\n"
"\n"
"	float t0 = fmax(fmax(fmax(tNear.x, tNear.y), fmax(tNear.x, tNear.z)), mint);\n"
"    float t1 = fmin(fmin(fmin(tFar.x, tFar.y), fmin(tFar.x, tFar.z)), maxt);\n"
"\n"
"	return (t1 > t0);\n"
"}\n"
; } }
