#include <string>
namespace luxrays { namespace ocl {
std::string KernelSource_ray_types = 
"#line 2 \"ray_types.cl\"\n"
"\n"
"/***************************************************************************\n"
" * Copyright 1998-2017 by authors (see AUTHORS.txt)                        *\n"
" *                                                                         *\n"
" *   This file is part of LuxRender.                                       *\n"
" *                                                                         *\n"
" * Licensed under the Apache License, Version 2.0 (the \"License\");         *\n"
" * you may not use this file except in compliance with the License.        *\n"
" * You may obtain a copy of the License at                                 *\n"
" *                                                                         *\n"
" *     http://www.apache.org/licenses/LICENSE-2.0                          *\n"
" *                                                                         *\n"
" * Unless required by applicable law or agreed to in writing, software     *\n"
" * distributed under the License is distributed on an \"AS IS\" BASIS,       *\n"
" * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.*\n"
" * See the License for the specific language governing permissions and     *\n"
" * limitations under the License.                                          *\n"
" ***************************************************************************/\n"
"\n"
"#define RAY_FLAGS_NONE   0x00000000\n"
"#define RAY_FLAGS_MASKED 0x00000001\n"
"\n"
"typedef struct {\n"
"	Point o;\n"
"	Vector d;\n"
"	float mint, maxt, time;\n"
"\n"
"	unsigned int flags;\n"
"	float pad[2]; // Add padding to avoid size discrepancies between OpenCL and C++\n"
"} Ray;\n"
"\n"
"typedef struct {\n"
"	float t, b1, b2;\n"
"	unsigned int meshIndex, triangleIndex;\n"
"} RayHit;\n"
; } }
