#include <string>
namespace luxrays { namespace ocl {
std::string KernelSource_trianglemesh_types = 
"#line 2 \"trianglemesh_types.cl\"\n"
"\n"
"/***************************************************************************\n"
" * Copyright 1998-2015 by authors (see AUTHORS.txt)                        *\n"
" *                                                                         *\n"
" *   This file is part of LuxRender.                                       *\n"
" *                                                                         *\n"
" * Licensed under the Apache License, Version 2.0 (the \"License\");         *\n"
" * you may not use this file except in compliance with the License.        *\n"
" * You may obtain a copy of the License at                                 *\n"
" *                                                                         *\n"
" *     http://www.apache.org/licenses/LICENSE-2.0                          *\n"
" *                                                                         *\n"
" * Unless required by applicable law or agreed to in writing, software     *\n"
" * distributed under the License is distributed on an \"AS IS\" BASIS,       *\n"
" * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.*\n"
" * See the License for the specific language governing permissions and     *\n"
" * limitations under the License.                                          *\n"
" ***************************************************************************/\n"
"\n"
"typedef struct {\n"
"	// Vertex informaiton\n"
"	unsigned int vertsOffset;\n"
"	unsigned int normalsOffset;\n"
"	unsigned int uvsOffset;\n"
"	unsigned int colsOffset;\n"
"	unsigned int alphasOffset;\n"
"\n"
"	// Triangle information\n"
"	unsigned int trisOffset;\n"
"\n"
"	// Object space transformation\n"
"	Transform trans;\n"
"} Mesh;\n"
; } }
