# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Dati/Various/Personal/Devel/luxcorerender/LuxCore/src/pyluxcoretools/pyluxcoretools/pyluxcorenetnode/mainwindow.ui',
# licensing of 'C:/Dati/Various/Personal/Devel/luxcorerender/LuxCore/src/pyluxcoretools/pyluxcoretools/pyluxcorenetnode/mainwindow.ui' applies.
#
# Created: Sat Jan 12 17:36:34 2019
#      by: pyside2-uic  running on PySide2 5.12.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frameNodeConfig = QtWidgets.QFrame(self.centralwidget)
        self.frameNodeConfig.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameNodeConfig.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameNodeConfig.setObjectName("frameNodeConfig")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frameNodeConfig)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_7 = QtWidgets.QLabel(self.frameNodeConfig)
        self.label_7.setTextFormat(QtCore.Qt.RichText)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_2.addWidget(self.label_7)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.frameNodeConfig)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.frameNodeConfig)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_4 = QtWidgets.QLabel(self.frameNodeConfig)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_3 = QtWidgets.QLabel(self.frameNodeConfig)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_5 = QtWidgets.QLabel(self.frameNodeConfig)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.lineEditIPAddress = QtWidgets.QLineEdit(self.frameNodeConfig)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditIPAddress.sizePolicy().hasHeightForWidth())
        self.lineEditIPAddress.setSizePolicy(sizePolicy)
        self.lineEditIPAddress.setMinimumSize(QtCore.QSize(250, 0))
        self.lineEditIPAddress.setInputMask("")
        self.lineEditIPAddress.setMaxLength(15)
        self.lineEditIPAddress.setObjectName("lineEditIPAddress")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEditIPAddress)
        self.lineEditPort = QtWidgets.QLineEdit(self.frameNodeConfig)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditPort.sizePolicy().hasHeightForWidth())
        self.lineEditPort.setSizePolicy(sizePolicy)
        self.lineEditPort.setMinimumSize(QtCore.QSize(100, 0))
        self.lineEditPort.setBaseSize(QtCore.QSize(0, 0))
        self.lineEditPort.setInputMask("")
        self.lineEditPort.setMaxLength(5)
        self.lineEditPort.setObjectName("lineEditPort")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEditPort)
        self.lineEditBroadcastAddress = QtWidgets.QLineEdit(self.frameNodeConfig)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditBroadcastAddress.sizePolicy().hasHeightForWidth())
        self.lineEditBroadcastAddress.setSizePolicy(sizePolicy)
        self.lineEditBroadcastAddress.setMinimumSize(QtCore.QSize(250, 0))
        self.lineEditBroadcastAddress.setObjectName("lineEditBroadcastAddress")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEditBroadcastAddress)
        self.lineEditBroadcastPeriod = QtWidgets.QLineEdit(self.frameNodeConfig)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditBroadcastPeriod.sizePolicy().hasHeightForWidth())
        self.lineEditBroadcastPeriod.setSizePolicy(sizePolicy)
        self.lineEditBroadcastPeriod.setMinimumSize(QtCore.QSize(100, 0))
        self.lineEditBroadcastPeriod.setObjectName("lineEditBroadcastPeriod")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEditBroadcastPeriod)
        self.plainTextEditProps = QtWidgets.QPlainTextEdit(self.frameNodeConfig)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEditProps.sizePolicy().hasHeightForWidth())
        self.plainTextEditProps.setSizePolicy(sizePolicy)
        self.plainTextEditProps.setMinimumSize(QtCore.QSize(0, 50))
        self.plainTextEditProps.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.plainTextEditProps.setObjectName("plainTextEditProps")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.plainTextEditProps)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButtonResetConfiguration = QtWidgets.QPushButton(self.frameNodeConfig)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonResetConfiguration.sizePolicy().hasHeightForWidth())
        self.pushButtonResetConfiguration.setSizePolicy(sizePolicy)
        self.pushButtonResetConfiguration.setObjectName("pushButtonResetConfiguration")
        self.horizontalLayout_2.addWidget(self.pushButtonResetConfiguration)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.label_6 = QtWidgets.QLabel(self.frameNodeConfig)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.verticalLayout.addWidget(self.frameNodeConfig)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButtonStartNode = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonStartNode.setObjectName("pushButtonStartNode")
        self.horizontalLayout.addWidget(self.pushButtonStartNode)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pushButtonStopNode = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonStopNode.setEnabled(False)
        self.pushButtonStopNode.setObjectName("pushButtonStopNode")
        self.horizontalLayout.addWidget(self.pushButtonStopNode)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.textEditLog = QtWidgets.QTextEdit(self.centralwidget)
        self.textEditLog.setUndoRedoEnabled(False)
        self.textEditLog.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.textEditLog.setReadOnly(True)
        self.textEditLog.setObjectName("textEditLog")
        self.verticalLayout.addWidget(self.textEditLog)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 25))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.actionQuit, QtCore.SIGNAL("activated()"), MainWindow.clickedQuit)
        QtCore.QObject.connect(self.pushButtonResetConfiguration, QtCore.SIGNAL("clicked()"), MainWindow.clickedResetConfig)
        QtCore.QObject.connect(self.pushButtonStartNode, QtCore.SIGNAL("clicked()"), MainWindow.clickedStartNode)
        QtCore.QObject.connect(self.pushButtonStopNode, QtCore.SIGNAL("clicked(bool)"), MainWindow.clickedStopNode)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "PyLuxCore Tool NetNode", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("MainWindow", "<B>Rendering Node Configuration<B>", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "Host name or IP address:", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "Port:", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWindow", "Broadcast period in secs:", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "Broadcast address:", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("MainWindow", "Custom LuxCore properties:", None, -1))
        self.pushButtonResetConfiguration.setText(QtWidgets.QApplication.translate("MainWindow", "Reset configuration", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("MainWindow", "Note: just press \"Start node\" button to use the default configuration", None, -1))
        self.pushButtonStartNode.setText(QtWidgets.QApplication.translate("MainWindow", "Start node", None, -1))
        self.pushButtonStopNode.setText(QtWidgets.QApplication.translate("MainWindow", "Stop node", None, -1))
        self.menuFile.setTitle(QtWidgets.QApplication.translate("MainWindow", "File", None, -1))
        self.actionQuit.setText(QtWidgets.QApplication.translate("MainWindow", "&Quit", None, -1))
        self.actionQuit.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+Q", None, -1))

