#line 2 "/home/david/projects/luxcorerender/LuxCore/src/luxcore/luxparser/luxlex.cpp"

#line 4 "/home/david/projects/luxcorerender/LuxCore/src/luxcore/luxparser/luxlex.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer luxcore_parserlxs_yy_create_buffer
#define yy_delete_buffer luxcore_parserlxs_yy_delete_buffer
#define yy_flex_debug luxcore_parserlxs_yy_flex_debug
#define yy_init_buffer luxcore_parserlxs_yy_init_buffer
#define yy_flush_buffer luxcore_parserlxs_yy_flush_buffer
#define yy_load_buffer_state luxcore_parserlxs_yy_load_buffer_state
#define yy_switch_to_buffer luxcore_parserlxs_yy_switch_to_buffer
#define yyin luxcore_parserlxs_yyin
#define yyleng luxcore_parserlxs_yyleng
#define yylex luxcore_parserlxs_yylex
#define yylineno luxcore_parserlxs_yylineno
#define yyout luxcore_parserlxs_yyout
#define yyrestart luxcore_parserlxs_yyrestart
#define yytext luxcore_parserlxs_yytext
#define yywrap luxcore_parserlxs_yywrap
#define yyalloc luxcore_parserlxs_yyalloc
#define yyrealloc luxcore_parserlxs_yyrealloc
#define yyfree luxcore_parserlxs_yyfree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE luxcore_parserlxs_yyrestart(luxcore_parserlxs_yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int luxcore_parserlxs_yyleng;

extern FILE *luxcore_parserlxs_yyin, *luxcore_parserlxs_yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up luxcore_parserlxs_yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up luxcore_parserlxs_yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via luxcore_parserlxs_yyrestart()), so that the user can continue scanning by
	 * just pointing luxcore_parserlxs_yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when luxcore_parserlxs_yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int luxcore_parserlxs_yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow luxcore_parserlxs_yywrap()'s to do buffer switches
 * instead of setting up a fresh luxcore_parserlxs_yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void luxcore_parserlxs_yyrestart (FILE *input_file  );
void luxcore_parserlxs_yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE luxcore_parserlxs_yy_create_buffer (FILE *file,int size  );
void luxcore_parserlxs_yy_delete_buffer (YY_BUFFER_STATE b  );
void luxcore_parserlxs_yy_flush_buffer (YY_BUFFER_STATE b  );
void luxcore_parserlxs_yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void luxcore_parserlxs_yypop_buffer_state (void );

static void luxcore_parserlxs_yyensure_buffer_stack (void );
static void luxcore_parserlxs_yy_load_buffer_state (void );
static void luxcore_parserlxs_yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER luxcore_parserlxs_yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE luxcore_parserlxs_yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE luxcore_parserlxs_yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE luxcore_parserlxs_yy_scan_bytes (yyconst char *bytes,int len  );

void *luxcore_parserlxs_yyalloc (yy_size_t  );
void *luxcore_parserlxs_yyrealloc (void *,yy_size_t  );
void luxcore_parserlxs_yyfree (void *  );

#define yy_new_buffer luxcore_parserlxs_yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        luxcore_parserlxs_yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            luxcore_parserlxs_yy_create_buffer(luxcore_parserlxs_yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        luxcore_parserlxs_yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            luxcore_parserlxs_yy_create_buffer(luxcore_parserlxs_yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *luxcore_parserlxs_yyin = (FILE *) 0, *luxcore_parserlxs_yyout = (FILE *) 0;

typedef int yy_state_type;

extern int luxcore_parserlxs_yylineno;

int luxcore_parserlxs_yylineno = 1;

extern char *luxcore_parserlxs_yytext;
#define yytext_ptr luxcore_parserlxs_yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up luxcore_parserlxs_yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	luxcore_parserlxs_yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 77
#define YY_END_OF_BUFFER 78
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[439] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       78,   76,   56,   57,   62,    8,   76,   76,   58,   59,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   59,   60,   61,   74,   75,   73,
       74,    9,   10,    4,    2,   77,    3,    6,    5,   56,
        0,   58,   58,   58,    0,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   72,   71,   68,   72,   69,   66,
       67,   63,   65,   64,    2,    7,   58,    0,   58,   59,

       59,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       59,    0,   59,   59,   59,   59,   59,   59,   59,   20,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   70,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   59,   43,   59,
       45,   59,   59,   59,   59,   59,   59,   59,   59,   15,

       59,   59,   59,   59,   59,   59,   59,   59,   59,   25,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   40,
       59,   59,   59,   59,   59,   59,   52,   59,   59,   59,
       59,   59,   59,   59,   59,   59,   59,    1,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   59,   41,   59,   59,   47,   59,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       19,   21,   22,   59,   59,   59,   26,   59,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   38,   59,   59,
       59,   59,   59,   59,   59,   55,   59,   59,   59,   59,

       59,   59,   59,   59,   59,   59,   30,   59,   59,   59,
       33,   59,   59,   59,   59,   59,   59,   59,   50,   51,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   23,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   59,   42,   59,   59,   59,   59,   54,   11,   59,
       59,   59,   59,   59,   59,   24,   59,   59,   29,   59,
       59,   32,   59,   37,   59,   44,   59,   59,   59,   59,
       59,   59,   59,   14,   59,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   59,   59,   49,   59,   59,   59,
       59,   59,   59,   59,   59,   59,   31,   59,   59,   59,

       59,   59,   59,   59,   13,   59,   59,   59,   59,   59,
       36,   34,   35,   59,   59,   48,   59,   12,   16,   59,
       59,   59,   28,   59,   59,   59,   59,   17,   59,   59,
       59,   53,   18,   27,   59,   46,   39,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    5,    1,    1,    1,    1,    1,
        1,    1,    6,    1,    6,    7,    1,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    1,    1,    1,
        1,    1,    1,    1,    9,   10,   11,   12,   13,   14,
       15,   12,   16,   12,   12,   17,   18,   19,   20,   21,
       12,   22,   23,   24,   12,   25,   26,   12,   12,   12,
       27,   28,   29,    1,   12,    1,   30,   31,   32,   33,

       34,   35,   36,   37,   38,   39,   40,   41,   42,   43,
       44,   45,   12,   46,   47,   48,   49,   50,   12,   51,
       52,   12,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[53] =
    {   0,
        1,    1,    2,    2,    1,    1,    1,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    1,    1,    1,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3
    } ;

static yyconst flex_int16_t yy_base[446] =
    {   0,
        0,    0,   50,   52,  490,  489,   55,   58,   60,   62,
      491,  494,  488,  494,  494,  494,   60,  481,   62,   39,
        0,   42,  437,  449,   40,   38,   44,  456,  454,   46,
       45,   61,   58,  440,  439,  494,  494,  494,  494,  494,
      108,  494,  494,  494,  480,  494,  494,    0,  494,  479,
      472,   92,   89,   93,  101,    0,  447,  444,  429,  434,
       70,  427,  433,  439,   71,  436,  427,   77,  422,  427,
      429,  416,  420,   65,  417,  422,  433,  432,  431,  414,
      408,  428,  416,  410,  494,  494,  494,  447,  494,  494,
      494,  494,  494,  494,  452,    0,  116,  445,  444,  417,

      420,  403,  414,  415,  400,  411,  402,  400,  401,  407,
      403,  399,  404,  403,  398,  401,  400,  399,  384,  398,
      396,  399,  383,  386,  380,  380,  389,  375,  379,  372,
      379,  411,  377,  400,  378,  369,  384,  380,  366,    0,
      363,  361,  363,  360,  398,  387,  359,  360,  370,  370,
      360,  370,  365,  352,  349,  355,  361,  362,  359,  362,
      342,  343,  347,  355,  494,  353,  348,  354,  354,  335,
       95,  344,  343,  347,  341,  105,  330,  347,  338,  332,
      356,  325,  358,  330,  324,  322,  334,  333,    0,  329,
        0,  333,  318,   96,  329,  122,  316,  325,  311,    0,

      335,  306,  314,  312,  307,  320,  309,  306,  307,    0,
      308,  319,  128,  318,  132,  309,  124,  312,  311,    0,
      298,  322,  308,  307,  296,  309,  322,  303,  293,  305,
      297,  285,  286,  284,  300,  283,  276,    0,  281,  282,
      276,  290,  282,  288,  278,  277,  271,  284,  274,  273,
      274,  271,  276,  266,  291,    0,  280,  293,    0,  262,
      259,  263,  269,  271,  255,  254,  267,  270,  275,  250,
        0,    0,    0,  248,  250,  262,    0,  258,  260,  245,
      257,  254,  256,  241,  239,  239,  255,    0,  238,  235,
      239,  239,  246,  231,  240,    0,  233,  253,  136,  232,

      228,  239,  227,  239,  134,  232,    0,  221,  222,  229,
        0,  218,  231,  216,  218,  224,  224,  212,  145,    0,
      225,  215,  211,  212,  221,  211,  206,  222,  228,    0,
      216,  219,  204,  204,  216,  207,  201,  213,  196,  211,
      206,  205,    0,  204,  203,  193,  199,    0,    0,  185,
      197,  199,  196,  187,  177,    0,  180,  186,    0,  183,
      195,    0,  181,    0,  180,    0,  179,  185,  184,  186,
      172,  171,  178,    0,  171,  167,  166,  178,  162,  178,
      168,  176,  175,  158,  159,  166,    0,  173,  170,  158,
      154,  164,  150,  151,  154,  161,    0,  160,  159,  162,

      161,  147,  141,  154,    0,  145,  142,  151,  146,  149,
        0,    0,    0,  134,  133,    0,  136,    0,    0,  133,
      136,  146,    0,  119,  109,   88,   88,    0,   81,   77,
       48,    0,    0,    0,   38,    0,    0,  494,  159,  162,
      165,  168,   74,  171,  174
    } ;

static yyconst flex_int16_t yy_def[446] =
    {   0,
      438,    1,  439,  439,  440,  440,  441,  441,  442,  442,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  443,
      443,  443,  443,  443,  443,  443,  443,  443,  443,  443,
      443,  443,  443,  443,  443,  438,  438,  438,  438,  438,
      444,  438,  438,  438,  438,  438,  438,  445,  438,  438,
      438,  438,  438,  438,  438,  443,  443,  443,  443,  443,
      443,  443,  443,  443,  443,  443,  443,  443,  443,  443,
      443,  443,  443,  443,  443,  443,  443,  443,  443,  443,
      443,  443,  443,  443,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  445,  438,  438,  438,  443,

      443,  443,  443,  443,  443,  443,  443,  443,  443,  443,
      443,  443,  443,  443,  443,  443,  443,  443,  443,  443,
      443,  443,  443,  443,  443,  443,  443,  443,  443,  443,
      443,  438,  443,  443,  443,  443,  443,  443,  443,  443,
      443,  443,  443,  443,  443,  443,  443,  443,  443,  443,
      443,  443,  443,  443,  443,  443,  443,  443,  443,  443,
      443,  443,  443,  443,  438,  443,  443,  443,  443,  443,
      443,  443,  443,  443,  443,  443,  443,  443,  443,  443,
      443,  443,  443,  443,  443,  443,  443,  443,  443,  443,
      443,  443,  443,  443,  443,  443,  443,  443,  443,  443,

      443,  443,  443,  443,  443,  443,  443,  443,  443,  443,
      443,  443,  443,  443,  443,  443,  443,  443,  443,  443,
      443,  443,  443,  443,  443,  443,  443,  443,  443,  443,
      443,  443,  443,  443,  443,  443,  443,  443,  443,  443,
      443,  443,  443,  443,  443,  443,  443,  443,  443,  443,
      443,  443,  443,  443,  443,  443,  443,  443,  443,  443,
      443,  443,  443,  443,  443,  443,  443,  443,  443,  443,
      443,  443,  443,  443,  443,  443,  443,  443,  443,  443,
      443,  443,  443,  443,  443,  443,  443,  443,  443,  443,
      443,  443,  443,  443,  443,  443,  443,  443,  443,  443,

      443,  443,  443,  443,  443,  443,  443,  443,  443,  443,
      443,  443,  443,  443,  443,  443,  443,  443,  443,  443,
      443,  443,  443,  443,  443,  443,  443,  443,  443,  443,
      443,  443,  443,  443,  443,  443,  443,  443,  443,  443,
      443,  443,  443,  443,  443,  443,  443,  443,  443,  443,
      443,  443,  443,  443,  443,  443,  443,  443,  443,  443,
      443,  443,  443,  443,  443,  443,  443,  443,  443,  443,
      443,  443,  443,  443,  443,  443,  443,  443,  443,  443,
      443,  443,  443,  443,  443,  443,  443,  443,  443,  443,
      443,  443,  443,  443,  443,  443,  443,  443,  443,  443,

      443,  443,  443,  443,  443,  443,  443,  443,  443,  443,
      443,  443,  443,  443,  443,  443,  443,  443,  443,  443,
      443,  443,  443,  443,  443,  443,  443,  443,  443,  443,
      443,  443,  443,  443,  443,  443,  443,    0,  438,  438,
      438,  438,  438,  438,  438
    } ;

static yyconst flex_int16_t yy_nxt[547] =
    {   0,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       22,   21,   23,   24,   21,   25,   26,   27,   28,   29,
       30,   31,   32,   33,   34,   35,   36,   12,   37,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   39,   40,   39,   40,   45,   46,   47,   45,
       46,   47,   46,   49,   46,   49,   51,   52,   54,   52,
       57,   60,   64,   68,   55,   66,   56,   41,   74,   41,
      437,   67,   65,   72,   58,   61,   59,   69,   75,   73,
       76,   81,   77,  436,   78,   55,   53,   79,   54,   52,

       97,   55,  109,   82,   55,   55,   98,  120,   99,   80,
       86,   87,  104,  105,  121,   88,  113,  202,  110,  208,
      435,  434,   55,   97,  114,   55,   55,  209,   55,  433,
      225,  228,  203,  432,  229,   89,  226,  244,   90,  252,
      245,  248,   91,  246,  249,  325,  253,  250,  326,   55,
       92,  332,  431,   93,  345,   94,  430,  346,  333,   38,
       38,   38,   42,   42,   42,   44,   44,   44,   48,   48,
       48,   85,   85,   85,   96,  429,   96,  428,  427,  426,
      425,  424,  423,  422,  421,  420,  419,  418,  417,  416,
      415,  414,  413,  412,  411,  410,  409,  408,  407,  406,

      405,  404,  403,  402,  401,  400,  399,  398,  397,  396,
      395,  394,  393,  392,  391,  390,  389,  388,  387,  386,
      385,  384,  383,  382,  381,  380,  379,  378,  377,  376,
      375,  374,  373,  372,  371,  370,  369,  368,  367,  366,
      365,  364,  363,  362,  361,  360,  359,  358,  357,  356,
      355,  354,  353,  352,  351,  350,  349,  348,  347,  344,
      343,  342,  341,  340,  339,  338,  337,  336,  335,  334,
      331,  330,  329,  328,  327,  324,  323,  322,  321,  320,
      319,  318,  317,  316,  315,  314,  313,  312,  311,  310,
      309,  308,  307,  306,  305,  304,  303,  302,  301,  300,

      299,  298,  297,  296,  295,  294,  293,  292,  291,  290,
      289,  288,  287,  286,  285,  284,  283,  282,  281,  280,
      279,  278,  277,  276,  275,  274,  273,  272,  271,  270,
      269,  268,  267,  266,  265,  264,  263,  262,  261,  260,
      259,  258,  257,  256,  255,  254,  251,  247,  243,  242,
      241,  240,  239,  238,  237,  236,  235,  234,  233,  232,
      231,  230,  227,  224,  223,  222,  221,  220,  219,  218,
      217,  216,  215,  214,  213,  212,  211,  210,  207,  206,
      205,  204,  201,  200,  199,  198,  197,  196,  195,  194,
      193,  192,  191,  190,  189,  188,  187,  186,  185,  184,

      183,  182,  181,  180,  179,  178,  177,  176,  175,  174,
      173,  172,  171,  170,  169,  168,  167,  166,  165,  164,
      163,  162,  161,  160,  159,  158,  157,  156,  155,  154,
      153,  152,  151,  150,  149,  148,  147,  146,  145,  144,
      143,  142,  141,  140,  139,  138,  137,  136,  135,  134,
      133,   99,   99,   95,  132,  131,  130,  129,  128,  127,
      126,  125,  124,  123,  122,  119,  118,  117,  116,  115,
      112,  111,  108,  107,  106,  103,  102,  101,  100,   53,
       50,   95,   84,   83,   71,   70,   63,   62,   53,   50,
      438,   43,   43,   11,  438,  438,  438,  438,  438,  438,

      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438
    } ;

static yyconst flex_int16_t yy_chk[547] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    3,    4,    4,    7,    7,    7,    8,
        8,    8,    9,    9,   10,   10,   17,   17,   19,   19,
       20,   22,   25,   27,   19,   26,  443,    3,   31,    4,
      435,   26,   25,   30,   20,   22,   20,   27,   31,   30,
       32,   33,   32,  431,   32,   19,   53,   32,   52,   52,

       54,   53,   65,   33,   52,   54,   55,   74,   55,   32,
       41,   41,   61,   61,   74,   41,   68,  171,   65,  176,
      430,  429,   53,   97,   68,   52,   54,  176,   97,  427,
      194,  196,  171,  426,  196,   41,  194,  213,   41,  217,
      213,  215,   41,  213,  215,  299,  217,  215,  299,   97,
       41,  305,  425,   41,  319,   41,  424,  319,  305,  439,
      439,  439,  440,  440,  440,  441,  441,  441,  442,  442,
      442,  444,  444,  444,  445,  422,  445,  421,  420,  417,
      415,  414,  410,  409,  408,  407,  406,  404,  403,  402,
      401,  400,  399,  398,  396,  395,  394,  393,  392,  391,

      390,  389,  388,  386,  385,  384,  383,  382,  381,  380,
      379,  378,  377,  376,  375,  373,  372,  371,  370,  369,
      368,  367,  365,  363,  361,  360,  358,  357,  355,  354,
      353,  352,  351,  350,  347,  346,  345,  344,  342,  341,
      340,  339,  338,  337,  336,  335,  334,  333,  332,  331,
      329,  328,  327,  326,  325,  324,  323,  322,  321,  318,
      317,  316,  315,  314,  313,  312,  310,  309,  308,  306,
      304,  303,  302,  301,  300,  298,  297,  295,  294,  293,
      292,  291,  290,  289,  287,  286,  285,  284,  283,  282,
      281,  280,  279,  278,  276,  275,  274,  270,  269,  268,

      267,  266,  265,  264,  263,  262,  261,  260,  258,  257,
      255,  254,  253,  252,  251,  250,  249,  248,  247,  246,
      245,  244,  243,  242,  241,  240,  239,  237,  236,  235,
      234,  233,  232,  231,  230,  229,  228,  227,  226,  225,
      224,  223,  222,  221,  219,  218,  216,  214,  212,  211,
      209,  208,  207,  206,  205,  204,  203,  202,  201,  199,
      198,  197,  195,  193,  192,  190,  188,  187,  186,  185,
      184,  183,  182,  181,  180,  179,  178,  177,  175,  174,
      173,  172,  170,  169,  168,  167,  166,  164,  163,  162,
      161,  160,  159,  158,  157,  156,  155,  154,  153,  152,

      151,  150,  149,  148,  147,  146,  145,  144,  143,  142,
      141,  139,  138,  137,  136,  135,  134,  133,  132,  131,
      130,  129,  128,  127,  126,  125,  124,  123,  122,  121,
      120,  119,  118,  117,  116,  115,  114,  113,  112,  111,
      110,  109,  108,  107,  106,  105,  104,  103,  102,  101,
      100,   99,   98,   95,   88,   84,   83,   82,   81,   80,
       79,   78,   77,   76,   75,   73,   72,   71,   70,   69,
       67,   66,   64,   63,   62,   60,   59,   58,   57,   51,
       50,   45,   35,   34,   29,   28,   24,   23,   18,   13,
       11,    6,    5,  438,  438,  438,  438,  438,  438,  438,

      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int luxcore_parserlxs_yy_flex_debug;
int luxcore_parserlxs_yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *luxcore_parserlxs_yytext;
#line 1 "/home/david/projects/luxcorerender/LuxCore/src/luxcore/luxparser/luxlex.l"
/***************************************************************************
 * Copyright 1998-2020 by authors (see AUTHORS.txt)                        *
 *                                                                         *
 *   This file is part of LuxCoreRender.                                   *
 *                                                                         *
 * Licensed under the Apache License, Version 2.0 (the "License");         *
 * you may not use this file except in compliance with the License.        *
 * You may obtain a copy of the License at                                 *
 *                                                                         *
 *     http://www.apache.org/licenses/LICENSE-2.0                          *
 *                                                                         *
 * Unless required by applicable law or agreed to in writing, software     *
 * distributed under the License is distributed on an "AS IS" BASIS,       *
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.*
 * See the License for the specific language governing permissions and     *
 * limitations under the License.                                          *
 ***************************************************************************/
#line 22 "/home/david/projects/luxcorerender/LuxCore/src/luxcore/luxparser/luxlex.l"

#define YY_MAIN 0
#define YY_NEVER_INTERACTIVE 1

#if defined(WIN32) && !defined(__CYGWIN__)
#pragma warning ( disable: 4244 )
#endif

#include <sstream>

#include <boost/foreach.hpp>
	
#include "luxcore/luxcore.h"
#include "luxrays/utils/utils.h"

#ifdef WIN32
#define YY_NO_UNISTD_H
#include <io.h>
#define isatty _isatty
#endif

struct ParamArray; // This is used but not defined inside luxparse.hpp
// luxparse.hpp is under "src" directory and not "include" because otherwise
// the parser sources are always recompiled (it is a bug in BISON_TARGET() cmake macro)
#include "luxparse.hpp"

using namespace std;
using namespace luxcore;

namespace luxcore { namespace parselxs {
	
struct IncludeInfo {
	string filename;
	YY_BUFFER_STATE bufState;
	u_int lineNum;
};
vector<IncludeInfo> includeStack;

extern u_int lineNum;
extern string currentFile;
int str_pos;

void AddStringChar( char c )
{
	if (str_pos == 1023) {
		LC_LOG("String is too long.");
		++str_pos;
	} else if (str_pos < 1023) {
		luxcore_parserlxs_yylval.string[str_pos++] = c;
		luxcore_parserlxs_yylval.string[str_pos] = '\0';
	}
}

extern void yyerror( const char *str );

void IncludePush(char *filename) {
	if (includeStack.size() > 32) {
		LC_LOG("Only 32 levels of nested Include allowed in scene files.");
    } else {
        FILE *newFile = fopen(filename, "r");
        if (!newFile) {
            LC_LOG("Unable to open included scene file: " << filename);
        } else {
            IncludeInfo ii;
            ii.filename = currentFile;
            ii.bufState = YY_CURRENT_BUFFER;
            ii.lineNum = lineNum;
            includeStack.push_back(ii);

            currentFile = filename;
            lineNum = 1;

        	luxcore_parserlxs_yyin = newFile;
        	luxcore_parserlxs_yy_switch_to_buffer(luxcore_parserlxs_yy_create_buffer(luxcore_parserlxs_yyin,YY_BUF_SIZE));
        }
    }
}

void IncludePop(void)
{
	// Close include file
	fclose(luxcore_parserlxs_yyin);
	luxcore_parserlxs_yy_delete_buffer(YY_CURRENT_BUFFER);
	luxcore_parserlxs_yy_switch_to_buffer(includeStack.back().bufState);
	currentFile = includeStack.back().filename;
	lineNum = includeStack.back().lineNum;
	includeStack.pop_back();
}

void IncludeClear()
{
	while (!includeStack.empty()) {
		luxcore_parserlxs_yy_delete_buffer(includeStack.back().bufState);
		includeStack.pop_back();		
	}
}

} }

using namespace luxcore::parselxs;


#line 864 "/home/david/projects/luxcorerender/LuxCore/src/luxcore/luxparser/luxlex.cpp"

#define INITIAL 0
#define STR 1
#define COMMENT 2
#define INCL 3
#define INCL_FILE 4

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int luxcore_parserlxs_yylex_destroy (void );

int luxcore_parserlxs_yyget_debug (void );

void luxcore_parserlxs_yyset_debug (int debug_flag  );

YY_EXTRA_TYPE luxcore_parserlxs_yyget_extra (void );

void luxcore_parserlxs_yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *luxcore_parserlxs_yyget_in (void );

void luxcore_parserlxs_yyset_in  (FILE * in_str  );

FILE *luxcore_parserlxs_yyget_out (void );

void luxcore_parserlxs_yyset_out  (FILE * out_str  );

int luxcore_parserlxs_yyget_leng (void );

char *luxcore_parserlxs_yyget_text (void );

int luxcore_parserlxs_yyget_lineno (void );

void luxcore_parserlxs_yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int luxcore_parserlxs_yywrap (void );
#else
extern int luxcore_parserlxs_yywrap (void );
#endif
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( luxcore_parserlxs_yytext, luxcore_parserlxs_yyleng, 1, luxcore_parserlxs_yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( luxcore_parserlxs_yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( luxcore_parserlxs_yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, luxcore_parserlxs_yyin))==0 && ferror(luxcore_parserlxs_yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(luxcore_parserlxs_yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int luxcore_parserlxs_yylex (void);

#define YY_DECL int luxcore_parserlxs_yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after luxcore_parserlxs_yytext and luxcore_parserlxs_yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 130 "/home/david/projects/luxcorerender/LuxCore/src/luxcore/luxparser/luxlex.l"


#line 1056 "/home/david/projects/luxcorerender/LuxCore/src/luxcore/luxparser/luxlex.cpp"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! luxcore_parserlxs_yyin )
			luxcore_parserlxs_yyin = stdin;

		if ( ! luxcore_parserlxs_yyout )
			luxcore_parserlxs_yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			luxcore_parserlxs_yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				luxcore_parserlxs_yy_create_buffer(luxcore_parserlxs_yyin,YY_BUF_SIZE );
		}

		luxcore_parserlxs_yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of luxcore_parserlxs_yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 439 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 494 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 132 "/home/david/projects/luxcorerender/LuxCore/src/luxcore/luxparser/luxlex.l"
{ BEGIN(INCL); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 133 "/home/david/projects/luxcorerender/LuxCore/src/luxcore/luxparser/luxlex.l"
;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 134 "/home/david/projects/luxcorerender/LuxCore/src/luxcore/luxparser/luxlex.l"
{ BEGIN(INCL_FILE); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 135 "/home/david/projects/luxcorerender/LuxCore/src/luxcore/luxparser/luxlex.l"
{ LC_LOG("Illegal character following Include directive"); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 136 "/home/david/projects/luxcorerender/LuxCore/src/luxcore/luxparser/luxlex.l"
{ BEGIN INITIAL; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 137 "/home/david/projects/luxcorerender/LuxCore/src/luxcore/luxparser/luxlex.l"
{  LC_LOG("Illegal character in Include file name"); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 138 "/home/david/projects/luxcorerender/LuxCore/src/luxcore/luxparser/luxlex.l"
{
	BEGIN(INITIAL);
	luxcore::parselxs::IncludePush(luxcore_parserlxs_yytext);
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 142 "/home/david/projects/luxcorerender/LuxCore/src/luxcore/luxparser/luxlex.l"
{ BEGIN COMMENT; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 143 "/home/david/projects/luxcorerender/LuxCore/src/luxcore/luxparser/luxlex.l"
/* eat it up */
	YY_BREAK
case 10:
/* rule 10 can match eol */
YY_RULE_SETUP
#line 144 "/home/david/projects/luxcorerender/LuxCore/src/luxcore/luxparser/luxlex.l"
{ lineNum++; BEGIN INITIAL; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 145 "/home/david/projects/luxcorerender/LuxCore/src/luxcore/luxparser/luxlex.l"
{ return ACCELERATOR; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 146 "/home/david/projects/luxcorerender/LuxCore/src/luxcore/luxparser/luxlex.l"
{ return AREALIGHTSOURCE;	}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 147 "/home/david/projects/luxcorerender/LuxCore/src/luxcore/luxparser/luxlex.l"
{ return ATTRIBUTEBEGIN; 	}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 148 "/home/david/projects/luxcorerender/LuxCore/src/luxcore/luxparser/luxlex.l"
{ return ATTRIBUTEEND; 		}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 149 "/home/david/projects/luxcorerender/LuxCore/src/luxcore/luxparser/luxlex.l"
{ return CAMERA;		}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 150 "/home/david/projects/luxcorerender/LuxCore/src/luxcore/luxparser/luxlex.l"
{ return CONCATTRANSFORM; 	}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 151 "/home/david/projects/luxcorerender/LuxCore/src/luxcore/luxparser/luxlex.l"
{ return COORDINATESYSTEM;	}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 152 "/home/david/projects/luxcorerender/LuxCore/src/luxcore/luxparser/luxlex.l"
{ return COORDSYSTRANSFORM;	}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 153 "/home/david/projects/luxcorerender/LuxCore/src/luxcore/luxparser/luxlex.l"
{ return EXTERIOR;		}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 154 "/home/david/projects/luxcorerender/LuxCore/src/luxcore/luxparser/luxlex.l"
{ return FILM;	 		}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 155 "/home/david/projects/luxcorerender/LuxCore/src/luxcore/luxparser/luxlex.l"
{ return IDENTITY;		}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 156 "/home/david/projects/luxcorerender/LuxCore/src/luxcore/luxparser/luxlex.l"
{ return INTERIOR;		}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 157 "/home/david/projects/luxcorerender/LuxCore/src/luxcore/luxparser/luxlex.l"
{ return LIGHTGROUP;		}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 158 "/home/david/projects/luxcorerender/LuxCore/src/luxcore/luxparser/luxlex.l"
{ return LIGHTSOURCE;		}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 159 "/home/david/projects/luxcorerender/LuxCore/src/luxcore/luxparser/luxlex.l"
{ return LOOKAT;		}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 160 "/home/david/projects/luxcorerender/LuxCore/src/luxcore/luxparser/luxlex.l"
{ return MATERIAL;		}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 161 "/home/david/projects/luxcorerender/LuxCore/src/luxcore/luxparser/luxlex.l"
{ return MAKENAMEDMATERIAL;	}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 162 "/home/david/projects/luxcorerender/LuxCore/src/luxcore/luxparser/luxlex.l"
{ return MAKENAMEDVOLUME;	}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 163 "/home/david/projects/luxcorerender/LuxCore/src/luxcore/luxparser/luxlex.l"
{ return MOTIONBEGIN;       }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 164 "/home/david/projects/luxcorerender/LuxCore/src/luxcore/luxparser/luxlex.l"
{ return MOTIONEND;         }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 165 "/home/david/projects/luxcorerender/LuxCore/src/luxcore/luxparser/luxlex.l"
{ return NAMEDMATERIAL;		}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 166 "/home/david/projects/luxcorerender/LuxCore/src/luxcore/luxparser/luxlex.l"
{ return OBJECTBEGIN;		}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 167 "/home/david/projects/luxcorerender/LuxCore/src/luxcore/luxparser/luxlex.l"
{ return OBJECTEND;		}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 168 "/home/david/projects/luxcorerender/LuxCore/src/luxcore/luxparser/luxlex.l"
{ return OBJECTINSTANCE;	}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 169 "/home/david/projects/luxcorerender/LuxCore/src/luxcore/luxparser/luxlex.l"
{ return PORTALINSTANCE;	}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 170 "/home/david/projects/luxcorerender/LuxCore/src/luxcore/luxparser/luxlex.l"
{ return MOTIONINSTANCE;	}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 171 "/home/david/projects/luxcorerender/LuxCore/src/luxcore/luxparser/luxlex.l"
{ return PIXELFILTER; 		}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 172 "/home/david/projects/luxcorerender/LuxCore/src/luxcore/luxparser/luxlex.l"
{ return RENDERER;	}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 173 "/home/david/projects/luxcorerender/LuxCore/src/luxcore/luxparser/luxlex.l"
{ return REVERSEORIENTATION;	}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 174 "/home/david/projects/luxcorerender/LuxCore/src/luxcore/luxparser/luxlex.l"
{ return ROTATE;		}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 175 "/home/david/projects/luxcorerender/LuxCore/src/luxcore/luxparser/luxlex.l"
{ return SAMPLER;		}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 176 "/home/david/projects/luxcorerender/LuxCore/src/luxcore/luxparser/luxlex.l"
{ return SEARCHPATH;		}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 177 "/home/david/projects/luxcorerender/LuxCore/src/luxcore/luxparser/luxlex.l"
{ return SCALE;			}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 178 "/home/david/projects/luxcorerender/LuxCore/src/luxcore/luxparser/luxlex.l"
{ return PORTALSHAPE;           }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 179 "/home/david/projects/luxcorerender/LuxCore/src/luxcore/luxparser/luxlex.l"
{ return SHAPE;			}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 180 "/home/david/projects/luxcorerender/LuxCore/src/luxcore/luxparser/luxlex.l"
{ return SURFACEINTEGRATOR;	}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 181 "/home/david/projects/luxcorerender/LuxCore/src/luxcore/luxparser/luxlex.l"
{ return TEXTURE;		}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 182 "/home/david/projects/luxcorerender/LuxCore/src/luxcore/luxparser/luxlex.l"
{ return TRANSFORMBEGIN;	}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 183 "/home/david/projects/luxcorerender/LuxCore/src/luxcore/luxparser/luxlex.l"
{ return TRANSFORMEND;	}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 184 "/home/david/projects/luxcorerender/LuxCore/src/luxcore/luxparser/luxlex.l"
{ return TRANSFORM;		}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 185 "/home/david/projects/luxcorerender/LuxCore/src/luxcore/luxparser/luxlex.l"
{ return TRANSLATE; 		}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 186 "/home/david/projects/luxcorerender/LuxCore/src/luxcore/luxparser/luxlex.l"
{ return VOLUME;		}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 187 "/home/david/projects/luxcorerender/LuxCore/src/luxcore/luxparser/luxlex.l"
{ return VOLUMEINTEGRATOR;	}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 188 "/home/david/projects/luxcorerender/LuxCore/src/luxcore/luxparser/luxlex.l"
{ return WORLDBEGIN; 		}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 189 "/home/david/projects/luxcorerender/LuxCore/src/luxcore/luxparser/luxlex.l"
{ return WORLDEND;		}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 190 "/home/david/projects/luxcorerender/LuxCore/src/luxcore/luxparser/luxlex.l"
/* do nothing */
	YY_BREAK
case 57:
/* rule 57 can match eol */
YY_RULE_SETUP
#line 191 "/home/david/projects/luxcorerender/LuxCore/src/luxcore/luxparser/luxlex.l"
{ lineNum++; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 192 "/home/david/projects/luxcorerender/LuxCore/src/luxcore/luxparser/luxlex.l"
{
  luxcore_parserlxs_yylval.num = static_cast<float>(atof(luxcore_parserlxs_yytext));
  return NUM;
}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 196 "/home/david/projects/luxcorerender/LuxCore/src/luxcore/luxparser/luxlex.l"
{
	strcpy(luxcore_parserlxs_yylval.string, luxcore_parserlxs_yytext);
	return ID;
}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 200 "/home/david/projects/luxcorerender/LuxCore/src/luxcore/luxparser/luxlex.l"
{ return LBRACK; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 201 "/home/david/projects/luxcorerender/LuxCore/src/luxcore/luxparser/luxlex.l"
{ return RBRACK; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 202 "/home/david/projects/luxcorerender/LuxCore/src/luxcore/luxparser/luxlex.l"
{ BEGIN STR; str_pos = 0; luxcore_parserlxs_yylval.string[0] = '\0';
	/* I have to initialize the string as an empty one in order to handle empty strings (i.e. "") */ }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 204 "/home/david/projects/luxcorerender/LuxCore/src/luxcore/luxparser/luxlex.l"
{AddStringChar('\n');}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 205 "/home/david/projects/luxcorerender/LuxCore/src/luxcore/luxparser/luxlex.l"
{AddStringChar('\t');}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 206 "/home/david/projects/luxcorerender/LuxCore/src/luxcore/luxparser/luxlex.l"
{AddStringChar('\r');}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 207 "/home/david/projects/luxcorerender/LuxCore/src/luxcore/luxparser/luxlex.l"
{AddStringChar('\b');}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 208 "/home/david/projects/luxcorerender/LuxCore/src/luxcore/luxparser/luxlex.l"
{AddStringChar('\f');}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 209 "/home/david/projects/luxcorerender/LuxCore/src/luxcore/luxparser/luxlex.l"
{AddStringChar('\"');}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 210 "/home/david/projects/luxcorerender/LuxCore/src/luxcore/luxparser/luxlex.l"
{AddStringChar('\\');}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 211 "/home/david/projects/luxcorerender/LuxCore/src/luxcore/luxparser/luxlex.l"
{
  char val = static_cast<char>(atoi(luxcore_parserlxs_yytext+1) & 0xff);
  AddStringChar(val);
}
	YY_BREAK
case 71:
/* rule 71 can match eol */
YY_RULE_SETUP
#line 215 "/home/david/projects/luxcorerender/LuxCore/src/luxcore/luxparser/luxlex.l"
{lineNum++;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 216 "/home/david/projects/luxcorerender/LuxCore/src/luxcore/luxparser/luxlex.l"
{ AddStringChar(luxcore_parserlxs_yytext[1]);}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 217 "/home/david/projects/luxcorerender/LuxCore/src/luxcore/luxparser/luxlex.l"
{BEGIN INITIAL; return STRING;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 218 "/home/david/projects/luxcorerender/LuxCore/src/luxcore/luxparser/luxlex.l"
{AddStringChar(luxcore_parserlxs_yytext[0]);}
	YY_BREAK
case 75:
/* rule 75 can match eol */
YY_RULE_SETUP
#line 219 "/home/david/projects/luxcorerender/LuxCore/src/luxcore/luxparser/luxlex.l"
{ LC_LOG("Unterminated string !");}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 221 "/home/david/projects/luxcorerender/LuxCore/src/luxcore/luxparser/luxlex.l"
{ LC_LOG("Illegal character " << (currentFile != "" ? "in file '" + std::string(currentFile) + "' " : "") << "at line " << lineNum << ": "<<luxcore_parserlxs_yytext[0]); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 222 "/home/david/projects/luxcorerender/LuxCore/src/luxcore/luxparser/luxlex.l"
ECHO;
	YY_BREAK
#line 1541 "/home/david/projects/luxcorerender/LuxCore/src/luxcore/luxparser/luxlex.cpp"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(STR):
case YY_STATE_EOF(COMMENT):
case YY_STATE_EOF(INCL):
case YY_STATE_EOF(INCL_FILE):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed luxcore_parserlxs_yyin at a new source and called
			 * luxcore_parserlxs_yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = luxcore_parserlxs_yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( luxcore_parserlxs_yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * luxcore_parserlxs_yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of luxcore_parserlxs_yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					luxcore_parserlxs_yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			luxcore_parserlxs_yyrestart(luxcore_parserlxs_yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) luxcore_parserlxs_yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 439 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 439 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 438);

	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					luxcore_parserlxs_yyrestart(luxcore_parserlxs_yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( luxcore_parserlxs_yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve luxcore_parserlxs_yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void luxcore_parserlxs_yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        luxcore_parserlxs_yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            luxcore_parserlxs_yy_create_buffer(luxcore_parserlxs_yyin,YY_BUF_SIZE );
	}

	luxcore_parserlxs_yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	luxcore_parserlxs_yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void luxcore_parserlxs_yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		luxcore_parserlxs_yypop_buffer_state();
	 *		luxcore_parserlxs_yypush_buffer_state(new_buffer);
     */
	luxcore_parserlxs_yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	luxcore_parserlxs_yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (luxcore_parserlxs_yywrap()) processing, but the only time this flag
	 * is looked at is after luxcore_parserlxs_yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void luxcore_parserlxs_yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	luxcore_parserlxs_yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE luxcore_parserlxs_yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) luxcore_parserlxs_yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in luxcore_parserlxs_yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) luxcore_parserlxs_yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in luxcore_parserlxs_yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	luxcore_parserlxs_yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with luxcore_parserlxs_yy_create_buffer()
 * 
 */
    void luxcore_parserlxs_yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		luxcore_parserlxs_yyfree((void *) b->yy_ch_buf  );

	luxcore_parserlxs_yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a luxcore_parserlxs_yyrestart() or at EOF.
 */
    static void luxcore_parserlxs_yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	luxcore_parserlxs_yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then luxcore_parserlxs_yy_init_buffer was _probably_
     * called from luxcore_parserlxs_yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void luxcore_parserlxs_yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		luxcore_parserlxs_yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void luxcore_parserlxs_yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	luxcore_parserlxs_yyensure_buffer_stack();

	/* This block is copied from luxcore_parserlxs_yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from luxcore_parserlxs_yy_switch_to_buffer. */
	luxcore_parserlxs_yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void luxcore_parserlxs_yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	luxcore_parserlxs_yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		luxcore_parserlxs_yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void luxcore_parserlxs_yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)luxcore_parserlxs_yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in luxcore_parserlxs_yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)luxcore_parserlxs_yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in luxcore_parserlxs_yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE luxcore_parserlxs_yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) luxcore_parserlxs_yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in luxcore_parserlxs_yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	luxcore_parserlxs_yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to luxcore_parserlxs_yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       luxcore_parserlxs_yy_scan_bytes() instead.
 */
YY_BUFFER_STATE luxcore_parserlxs_yy_scan_string (yyconst char * yystr )
{
    
	return luxcore_parserlxs_yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to luxcore_parserlxs_yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE luxcore_parserlxs_yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) luxcore_parserlxs_yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in luxcore_parserlxs_yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = luxcore_parserlxs_yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in luxcore_parserlxs_yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up luxcore_parserlxs_yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		luxcore_parserlxs_yytext[luxcore_parserlxs_yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = luxcore_parserlxs_yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		luxcore_parserlxs_yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int luxcore_parserlxs_yyget_lineno  (void)
{
        
    return luxcore_parserlxs_yylineno;
}

/** Get the input stream.
 * 
 */
FILE *luxcore_parserlxs_yyget_in  (void)
{
        return luxcore_parserlxs_yyin;
}

/** Get the output stream.
 * 
 */
FILE *luxcore_parserlxs_yyget_out  (void)
{
        return luxcore_parserlxs_yyout;
}

/** Get the length of the current token.
 * 
 */
int luxcore_parserlxs_yyget_leng  (void)
{
        return luxcore_parserlxs_yyleng;
}

/** Get the current token.
 * 
 */

char *luxcore_parserlxs_yyget_text  (void)
{
        return luxcore_parserlxs_yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void luxcore_parserlxs_yyset_lineno (int  line_number )
{
    
    luxcore_parserlxs_yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see luxcore_parserlxs_yy_switch_to_buffer
 */
void luxcore_parserlxs_yyset_in (FILE *  in_str )
{
        luxcore_parserlxs_yyin = in_str ;
}

void luxcore_parserlxs_yyset_out (FILE *  out_str )
{
        luxcore_parserlxs_yyout = out_str ;
}

int luxcore_parserlxs_yyget_debug  (void)
{
        return luxcore_parserlxs_yy_flex_debug;
}

void luxcore_parserlxs_yyset_debug (int  bdebug )
{
        luxcore_parserlxs_yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from luxcore_parserlxs_yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    luxcore_parserlxs_yyin = stdin;
    luxcore_parserlxs_yyout = stdout;
#else
    luxcore_parserlxs_yyin = (FILE *) 0;
    luxcore_parserlxs_yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * luxcore_parserlxs_yylex_init()
     */
    return 0;
}

/* luxcore_parserlxs_yylex_destroy is for both reentrant and non-reentrant scanners. */
int luxcore_parserlxs_yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		luxcore_parserlxs_yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		luxcore_parserlxs_yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	luxcore_parserlxs_yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * luxcore_parserlxs_yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *luxcore_parserlxs_yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *luxcore_parserlxs_yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void luxcore_parserlxs_yyfree (void * ptr )
{
	free( (char *) ptr );	/* see luxcore_parserlxs_yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 222 "/home/david/projects/luxcorerender/LuxCore/src/luxcore/luxparser/luxlex.l"


int luxcore_parserlxs_yywrap(void)
{
	if (includeStack.size() ==0) return 1;
	IncludePop();
	BEGIN(INCL_FILE);
	return 0;
}

